### ISSUE TITLE
Guide for migration from EC2 scheduler.

### ISSUE THREAD

**Issue by dburbridge** [awslabs/aws-instance-scheduler#1]
Hi,

This is awesome, just what I was looking for.
We have been using the EC2 scheduler for some time now and have been looking to expand it to schedule RDS stop/start times as well.
Do you have a guide/strategy/advice for migration from the EC2 scheduler?

**Comment by alexdej1967** [comment]
This python scrip will print the commands for the scheduler-cli and aws cli to create new schedules from the existing tags and tag the instances with the new schedule names.
1) Deactivate legacy scheduler
2) Run python script below, pass the region, name of the new scheduler stack and he new tag (Schedule) you are using in the new stack
3) Review the generated commands, optionally rename the generated schedule/period names and run the commands to create the new schedules and tag the instances. 
4) delete the old tags using the tag editor

import boto3
import sys

new_schedule_tag_name = None
region = None
stack = None

periods = {}
schedules = {}
instance_tags = {}


# import settings from old ec2 scheduler
def get_old_scheduler_settings():
    db = boto3.client("dynamodb", region_name=region)
    return db.get_item(TableName="EC2-Scheduler", Key={"SolutionName": {"S": "EC2Scheduler"}}).get("Item", {})


# get instances scheduled by the old scheduler, filtered by the tag from the settings
def get_scheduled_instances(settings):
    ec2 = boto3.client("ec2", region_name=region)
    args = {}
    while True:
        resp = ec2.describe_instances(**args)
        for reservation in resp.get("Reservations", []):
            for instance in reservation.get("Instances", []):
                for tag in instance.get("Tags", {}):
                    if tag["Key"].startswith(settings["CustomTagName"]["S"]):
                        yield instance
                        break
        if "NextToken" in resp:
            args["NextToken"] = resp["NextToken"]
        else:
            break


# new scheduler uses hh:mm format
def time_str(s):
    return "{}:{}".format(s[0:len(s) - 2], s[-2:])


# formats day names, commas are removed from list as these can not be used in RDS tags
def days_str(s):
    return "".join([d.strip() for d in s.split(",")])


# build internal schedule for default settings in old scheduler
def get_default_schedule(settings):
    return {
        "begintime": settings["DefaultStartTime"]["S"],
        "endtime": settings["DefaultStopTime"]["S"],
        "timezone": "UTC",
        "weekdays": days_str(settings["DefaultDaysActive"]["S"]),
        "default": True
    }


# build internal schedule from oldtag nased schedule
def get_tag_schedule(tag_value):
    tag_parts = tag_value.split(";")

    tag_schedule = {
        "begintime": None,
        "endtime": None,
        "timezone": "UTC",
        "weekdays": None,
        "default": False
    }

    if len(tag_parts) >= 1:
        tag_schedule["begintime"] = tag_parts[0]
        tag_schedule["endtime"] = tag_parts[0]
    if len(tag_parts) >= 2:
        tag_schedule["endtime"] = tag_parts[1]
    if len(tag_parts) >= 3:
        tag_schedule["timezone"] = tag_parts[2]
    if len(tag_parts) >= 4:
        tag_schedule["weekdays"] = tag_parts[3].lower()

    return tag_schedule


# build key for period
def period_as_str(p):
    if p["default"]:
        return "DefaultPeriod"
    return "Period-{}{}-{}".format(p["begintime"], p["endtime"], days_str(p["weekdays"]))


# get string to use as key for schedule
def get_schedule_name(period):
    if period["default"]:
        return "DefaultSchedule"
    return "{}-{}".format(period_as_str(period).replace("Period", "Schedule"), period["timezone"])


# create command for scheduler-cli to create period
def create_period_cli(period_name):
    period = periods[period_name]
    return "scheduler-cli create-period --stack {} --region {} --name {} --begintime {} --endtime {} {}".format(
        stack, region, period_name, time_str(period["begintime"]), time_str(period["endtime"]),
        ("--weekdays {}".format(period["weekdays"])) if period["weekdays"].lower() != "all" else "")


# create command for scheduler-cli to create schedule
def create_schedule_cli(schedule_name):
    return "scheduler-cli create-schedule --stack {} --region {} --name {} --periods {} --timezone {}".format(
        stack, region, schedule_name, schedules[schedule_name], periods[schedules[schedule_name]]["timezone"])


# creare command to tag new tag for EC2 instances
def create_tag_cli(instance_id):
    return "aws ec2 create-tags --resources {} --tags Key={},Value={} --region {}".format(instance_id, new_schedule_tag_name,
                                                                                          instance_tags[instance_id], region)


# Uses tags from instance to collect new schedules/period information and instance tags
def build_schedule_and_perod_from_legacy_tag(default_schedule, i, old_schedule_tag_name):
    legacy_schedule = None
    for t in i.get("Tags", []):
        if t["Key"].startswith(old_schedule_tag_name):
            tagvalue = t.get("Value", "")
            if tagvalue.lower() in ["default", "true"]:
                legacy_schedule = default_schedule
            else:
                legacy_schedule = get_tag_schedule(tagvalue)
            break
    if legacy_schedule is not None:

        period_name = (period_as_str(legacy_schedule))

        if period_name not in periods:
            periods[period_name] = legacy_schedule

        schedule_name = get_schedule_name(legacy_schedule)
        if schedule_name not in schedules:
            schedules[schedule_name] = period_name

        instance_tags[i["InstanceId"]] = schedule_name


def get_script_parameters():
    global region, stack, new_schedule_tag_name
    if len(sys.argv) != 4:
        print("Usage is {} <region-name> <name-of-new-scheduler-stack> <name-of-new-schedule-tag>".format(
            sys.argv[0].split("/")[-1], ))
        exit(1)
    region = sys.argv[1]
    stack = sys.argv[2]
    new_schedule_tag_name = sys.argv[3]


def main():
    settings = get_old_scheduler_settings()
    instances = list(get_scheduled_instances(settings))

    default_schedule = get_default_schedule(settings)
    old_schedule_tag_name = settings["CustomTagName"]["S"]

    for i in instances:
        build_schedule_and_perod_from_legacy_tag(default_schedule, i, old_schedule_tag_name)

    for p in periods:
        print(create_period_cli(p))

    for s in schedules:
        print(create_schedule_cli(s))

    for i in instance_tags:
        print(create_tag_cli(i))


if __name__ == '__main__':
    get_script_parameters()
    main()

**Comment by shsenior** [comment]
Closing due to time elapsed since last correspondence. Please re-open this if you are still having an issue.
