### ISSUE TITLE
Error when create_rds_snapshot is set to false

### ISSUE THREAD

**Issue by perrucci-sara** [awslabs/aws-instance-scheduler#104]
Hello,

trying to setup scheduled shutdown os some RDS instances, I get the error

ERROR : Error stopping rds instance RDS:xxx (xxx), (local variable 'snapshot_name' referenced before assignment)

if snapshot creation is set to false.
Looking at the lambda code in rds_service.py:349

            if does_snapshot_exist(snapshot_name):
                client.delete_db_snapshot_with_retries(DBSnapshotIdentifier=snapshot_name)
                self._logger.info(INF_DELETE_SNAPSHOT, snapshot_name)

If snapshot creation is disabled, snapshot_name is not assigned, hence the error.

Paolo

**Comment by alidgett** [comment]
I have the same error - for development RDS instances I don't need to snapshot the DB.

Thanks
Andrew

**Comment by grinszju** [comment]
Hi,

just need to initalize snapshot_name (to whatever) in rds_service.py and it works.

Regards

**Comment by georgebearden** [comment]
This issue should be resolved in the latest release.
