### ISSUE TITLE
Schedule to start on sunday and only to be stopped on friday

### ISSUE THREAD

**Issue by lovepurohit** [awslabs/aws-instance-scheduler#109]
I want to schedule the instance with the start time on the sunday say 18:00 CST and which needs to be stopped on friday say 19:00 CST.

Is there any way to approach this. I am confused on how many periods would be needed to achieve this?

Thank you

**Comment by maximrozin** [comment]
https://docs.aws.amazon.com/solutions/latest/instance-scheduler/appendix-e.html

**Comment by lovepurohit** [comment]
Thanks maximrozin. I was thinking the same but thought that I should confirm it first.

Thank you for the help
