### ISSUE TITLE
docdb DB instances are not eligible for stopping and starting

### ISSUE THREAD

**Issue by jia2015** [awslabs/aws-instance-scheduler#111]
Hi,

I am getting the following error.
"errorCode": "InvalidParameterCombinationException", 
"errorMessage": "docdb DB instances are not eligible for stopping and starting.",
Any idea?

Thanks,

**Comment by georgebearden** [comment]
Hi, 

Can you provide a small clarification. What type of database are you trying to schedule here? Only RDS Instances and Aurora Clusters are supported.

**Comment by jia2015** [comment]
document db

**Comment by georgebearden** [comment]
Thank you for that info. So currently you can only use the Instance Scheduler solution to schedule EC2 Instances, RDS Instances, and Aurora Clusters. I will create a new feature request for DocumentDB support to be evaluated in an upcoming release.

**Comment by brianmjones** [comment]
Did this ever get implemented?  I can't find "a new feature request" for this.  @georgebearden
