### ISSUE TITLE
No PR ever merged

### ISSUE THREAD

**Issue by neg3ntropy** [awslabs/aws-instance-scheduler#112]
I just made a small fix and I am about to start investigating another issue. I was going to open a PR for the fix, but I noticed that never once this project has merged a PR from github.

Since I already wasted my time once, I would like to understand if PR are welcome at all. Otherwise I can just maintain some stuff on my own and still be thankful for whatever I got.

I would consider the present issue resolved by either:
- an update of the contributing guidelines discouraging PRs
- a merged PR

**Comment by neg3ntropy** [comment]
FIY The two fixes are ready in https://github.com/tierratelematics/aws-instance-scheduler

**Comment by georgebearden** [comment]
Hi Andrea - I just reviewed the changes, and they look great. Apologies for work done in the past that was never picked up... We absolutely accept community contributions into future releases of this project (and more generally our Solutions we release on GitHub). I want to make sure that does not happen again. Let me provide some clarity to the process we have to follow and please let me know if you have any questions. 

We have internal development and deployment processes that we must follow before releasing updates to solutions. This is why when you look through commits, you will likely only see "Updated to version X.Y.Z". We can take PRs submitted from the community, but right now we have to manually pull them into our internal repositories, run the changes through our CI/CD processes, and then bundle the changes into a new release that we put on GitHub. The unfortunate side effect of this is is that the original PR submitted from the GitHub repo is no longer connected to the updated code.

Your contributions are greatly appreciated! I am working on consolidating PRs and changes into the next upcoming release of Instance Scheduler and will update this issue with more details as they become available.

**Comment by neg3ntropy** [comment]
Hello @georgebearden. here's an idea:
- you could make this repo a submodule of your private one and keep the extra CI/deployement scripts in there.
- you can configure multiple git remotes, allowing code to flow both ways, consistent changelogs and PRs.
- a separate development branch would let you accept code without necessarily releasing it, and with the possibility of later revert if it fails internal QA.

All that needs hiding, should be well hidden, but it's best to develop as openly as possible.

About the fixes, do you want PRs or what do we do?

**Comment by georgebearden** [comment]
Thank you for that idea Andrea. I'm taking it back to the team to discuss soon. As for the PRs, the rds snapshot fix is much appreciated. I'm not sure yet if parts of the build process changes will be able to be taken as is, but if you can submit the PR for that soI can review.

**Comment by neg3ntropy** [comment]
you have all three PRs.
There might be more in the future, so I hope you manage to really have development of this code in the open.

**Comment by georgebearden** [comment]
Hi Andrea - Just a quick update that we are working to consolidate several of the PRs you and others have submitted. Thank you again for the contributions.

**Comment by georgebearden** [comment]
Hi @neg3ntropy - We've just released an update to this solution that incorporated the PRs you posted along with others that were submitted. Sorry for the delay, but really appreciate your help and patience. For now we are still following the release process I described above, but again, I'm grateful for your suggestions and hope to have improvements in the future that you will see.
