### ISSUE TITLE
ClientError: An error occurred (ValidationException) when calling the PutItem operation: Item size has exceeded the maximum allowed size

### ISSUE THREAD

**Issue by pennywisdom** [awslabs/aws-instance-scheduler#113]
Hi, does this error indicate that we have too many schedule and period rules defined? Are there limits? 
The error is being reported in response to the scheduler.run action.

At the moment, I continually receive this exception on each run (every 5 mins).

Thanks

**Comment by arieleeuw** [comment]
Hi,
This might be caused in case there are too many items in the row for the account/region/service in the state table. How many instances are you or did trying to schedule? You can clear the row from the table to reset the state management that is using this table

**Comment by pennywisdom** [comment]
Hi @arieleeuw the row is indeed larger than the 400Kb. In fact the console crashes both chrome and opera when trying to view it. I will check using the CLI.

**Comment by arieleeuw** [comment]
Normally the entries are removed automatically after a instance is not longer "seen" by the scheduler. In rare cases, especially when having many temporary instances, it might be required to clear the row manually. The state table will build itself for the instances that are still there.

**Comment by pennywisdom** [comment]
Thanks, @arieleeuw . Yep I removed and recreated the table and have seen that the state is rebuilt. BTW, are there any maintenance cli commands that can be run to clean / clear the state table or is it best just to delete the table then recreate?

**Comment by arieleeuw** [comment]
Good to hear his solved your problem. If the console does not work for you then the best way to do this is to use the aws cli for dynamodb.

https://docs.aws.amazon.com/cli/latest/reference/dynamodb/delete-item.html
