### ISSUE TITLE
Every `X` day does not work (e.g. every third wednesday `wed#3`)

### ISSUE THREAD

**Issue by philip-ulrich** [awslabs/aws-instance-scheduler#114]
Hello Friends,

Running into an issue with instance scheduler. Trying to get it to run a schedule once a month on a certain day and it is instead running it everyday. You can find below relevant portions of the config being used below:

```
"type (S)","name (S)","description (S)","weekdays (SS)","periods (SS)","timezone (S)","begintime (S)","endtime (S)","use_metrics (BOOL)","enforced (BOOL)","override_status (S)","retain_running (BOOL)","stop_new_instances (BOOL)","default_timezone (S)","months (SS)","regions (SS)","schedule_lambda_account (BOOL)","scheduled_services (SS)","started_tags (S)","stopped_tags (S)","tagname (S)","trace (BOOL)"
"period","patch-hours",,"{ ""wed#3"" } ",,,"21:30","23:59",,,,,,,,,,,,,,
"period","period-nz-office-hours",,"{ ""mon-fri"" } ",,,"08:00","18:00",,,,,,,,,,,,,,
"schedule","nz-office-hours",,,"{ ""patch-hours"", ""period-nz-office-hours"" } ","Pacific/Auckland",,,,"false",,"false","true",,,,,,,,,
```

Debug output is enabled and showing the following for the detected configuration on those items: 

```
            "period-nz-office-hours": {
                "endtime": "18:00",
                "begintime": "08:00",
                "weekdays": [
                    0,
                    1,
                    2,
                    3,
                    4
                ]
            },
            "patch-hours": {
                "endtime": "23:59",
                "begintime": "21:30"
            },
```

Are you able to help determine what is going on? This is a rather time sensitive issue.

To help clarify, the intended desire here is to run a normal schedule, but then power it on for a couple hours one day a month for patching. Presently it is just doing it every night.

**Comment by arieleeuw** [comment]
Hi Philip,
In the first version of the scheduler there was a bug in the # logic, which should be fixed in the latest release. Did you install the latest version (or a stack update) from the latest template?
In order to find out why the scheduler starts/stops the Instance, enable detailed logging. Find the start/stop moment in the log file for the specific service/region where there  is detailed information of every period evaluation and the outcome of the desired state.
Hope this helps.

**Comment by philip-ulrich** [comment]
Thanks for that info. I'm showing the version of the template as "Instance scheduler, version 2.2.2.0". So I'm guessing I will need to upgrade (downgrade?) to 1.2.0. I'll give that a shot and report back.

**Comment by arieleeuw** [comment]
1.2.0 is the latest release.  The 2.2.2.0 is a number we use internally for the builds

**Comment by philip-ulrich** [comment]
Sorry for the delay. The new version of instance scheduler did not start logging right away and I was OOO yesterday. Checked in today and it looks like it's not starting up every night now (yay!), but debug showing the following for config:            

           "patch-hours": {
                "endtime": "23:59",
                "begintime": "21:30",
                "weekdays": []
            },

I would think that it should be showing the `wed#3`, but it's not. Can you confirm if this is expected or not? We are approaching the third wednesday so we'll see shortly, but I need these instances powered on for patching.

**Comment by arieleeuw** [comment]
Hi,
Good to hear the new version is working for you.
What do you see when you list the period using the list-periods sub command?
Regards
Arie

**Comment by philip-ulrich** [comment]
I've never used the CLI before, but after getting it set up it looks to be reading it correctly: 

```
      {
         "Description": "Patching hours", 
         "Weekdays": [
            "wed#3"
         ], 
         "Begintime": "21:50", 
         "Endtime": "23:00", 
         "Type": "period", 
         "Name": "patch-hours"
      }, 
```

I think this is resolved. Thanks for the quick replies and assistance. 😃
