### ISSUE TITLE
SSM Parameter limit reached when too many cross-account roles

### ISSUE THREAD

**Issue by ozeebee** [awslabs/aws-instance-scheduler#120]
Hi guys,
I'm opening this ticket because I have to specify a long list of cross-account roles for the scheduler (>100).
I'm using a _standard_ SSM parameter which means I'm limited to 4096 characheters that roughly represent 42 accounts.
I know I can pay for an _advanced_ parameter which doubles the limit (8129 charachters) but still I'm limited to ~85 accounts in this case.

I know there's a similar limitation when using the old way (CF/dynamo db field) to handle cross-account roles.
A colleague working on another project had to install the solution 3 times to overcome this limitation... and I would like to avoid this if possible.

Any chance to have a fix / more scalable solution for this use case ?

Thanks.

**Comment by arieleeuw** [comment]
Hi,
It is possible to include multiple SSM string parameters or list parameters placeholders in the cross account roles parameter. Would this work for you?

**Comment by ozeebee** [comment]
Hi,
Even though it's not yet the silver bullet, it would be much less burdensome (and onerous) to split the account list in a few parameters than duplicating the entire stack.

Is it already implemented ? (can I put multiple SSM params in the template parameter) or do you have to implement it ?

Many thanks!

**Comment by arieleeuw** [comment]
In the latest version that is available you can use multiply references to SSM parameters in the comma separated list. Syntax is described in the guide. 
In Ops Automator 2 we used a new approach that let you specify just the account numbers for cross account operations, but so far this method has not been used for Instance Scheduler.

**Comment by ozeebee** [comment]
Ok, I tested with two parameters and it works.
Might be useful to highlight this in the documentation.
Thanks for your help, I guess that now the only limit is the number of parameter names we can put in the CF parameter template (to reach this means one would have to configure hundreds or even thousands of accounts...)
