### ISSUE TITLE
hard limit of number of cross account role arns that can be passed as an environment variable

### ISSUE THREAD

**Issue by ziyadmhd** [awslabs/aws-instance-scheduler#126]
Hi,
When i add a lot of role arns to the "cross_account_roles" parameter as a cloudformation environment variable, it says it hit a hard limit of 4096 characters on the environment variable. AWS support instead asked me to split the parameter to 2 and join them using Fn::Join. That doesn't work either. This is what i did :

"cross_account_roles":{
              "Fn::Join": [
                ",", [
                  {
                    "Ref":"CrossAccountRoles1"
                  },
                  {
                    "Ref":"CrossAccountRoles2"
                  }
                ]
              ]
            },

It gives me this error - 
aws_cloudformation_stack.stack: ValidationError: Template error: every Fn::Join object requires two parameters, (1) a string delimiter and (2) a list of strings to be joined or a function that returns a list of strings (such as Fn::GetAZs) to be joined

**Comment by arieleeuw** [comment]
For this situations we have the option to use SSM parameter lists as described at https://docs.aws.amazon.com/solutions/latest/instance-scheduler/components.html, section Cross-Account Instance Scheduling. You can store lists of cross account role arn's in one or more ssm parameter store list parameterts and then include the names of the parameters in the cross account roles parameter in the format {param:<name of parameter>}, {param:<name of parameter>}, etc..

**Comment by ziyadmhd** [comment]
will the parameter after this will be like this ?
CrossAccountRoles = param:rolearnsSSM (if my parameter name is rolearnsSSM)

**Comment by arieleeuw** [comment]
the format is 
`{param:paramname}
`

If you want you can have multiple of these entries in the CrossAccountRoles parameters
`{param:paramname1},{param:paramname2}`

Or you can combine them with arns 
`{param:paramname1},cross-accountrole-arn,{param:paramname2}`
