### ISSUE TITLE
RDS upscale or downscale type

### ISSUE THREAD

**Issue by trotroyanas** [awslabs/aws-instance-scheduler#128]
Hi,

i have a multiple rds server.
i want to change up or down instance type of my servers..
nigth : down instance type db.m5.large
morning : up instance type db.m5.2xlarge 

rds start or stop are ok but no update or scale
in schedule part i call period like this : rds-period-tst@db.m4.2xlarge

a idea ?
thank.
cH.

**Comment by eduardovra** [comment]
+1

**Comment by dscpinheiro** [comment]
Hi @trotroyanas,

Sorry for the delay in the response.
We've added your feature request to the backlog for upcoming versions of this solution.

**Comment by lopesjeronimo** [comment]
Very nice feature. Is the project open for external pull requests? I would be happy to contribute especially if there is a minimum guideline on how to implement this feature.

**Comment by dscpinheiro** [comment]
Yes, we're open to pull requests!

Just make sure to read the [CONTRIBUTING](https://github.com/awslabs/aws-instance-scheduler/blob/master/CONTRIBUTING.md) and [CODE_OF_CONDUCT](https://github.com/awslabs/aws-instance-scheduler/blob/master/CODE_OF_CONDUCT.md) files you wish to contribute.

**Comment by trotroyanas** [comment]
+1

**Comment by maykays** [comment]
@trotroyanas the functionality that you describe can be achieved with Operations Conductor: [https://github.com/awslabs/operations-conductor](url)

**Comment by nifrasinnovent** [comment]
@maykays & @trotroyanas Is this functionality available in the aws-instance-scheduler itself now?
Please confirm it.
