### ISSUE TITLE
The scheduler only starts but doesn't stop instances

### ISSUE THREAD

**Issue by nguyendviet** [awslabs/aws-instance-scheduler#129]
I used the latest template to create the EC2 Scheduler with stackname: `EC2Scheduler` and no matter how I set up my office-time, the scheduler only starts the instances (if I manually stop them to test) but never stops them.

I changed the endtime to different time, lambda execution to every 1 minute, 2 minutes, etc.

get-item
```bash
{
    "Item": {
        "begintime": {
            "S": "08:00"
        },
        "description": {
            "S": "Office hours"
        },
        "endtime": {
            "S": "18:00"
        },
        "weekdays": {
            "SS": [
                "mon-fri"
            ]
        },
        "name": {
            "S": "office-hours"
        },
        "type": {
            "S": "period"
        }
    }
}

{
    "Item": {
        "use_metrics": {
            "BOOL": false
        },
        "override_status": {
            "S": "running"
        },
        "timezone": {
            "S": "America/New_York"
        },
        "description": {
            "S": "Instances running"
        },
        "periods": {
            "SS": [
                "office-hours"
            ]
        },
        "name": {
            "S": "running"
        },
        "type": {
            "S": "schedule"
        }
    }
}
```

**Comment by stevepop** [comment]
I have the same issue myself. I have deleted and re-created the scheduler a couple of times thinking I did something wrong but no dice. It never stops the instances.

**Comment by arieleeuw** [comment]
```
override_status": {
            "S": "running"
}
```

overwrites what’s in the periods. 
Instances tagged with this schedule will always be running.

**Comment by nguyendviet** [comment]
> ```
> override_status": {
>             "S": "running"
> }
> ```
> 
> overwrites what’s in the periods.
> Instances tagged with this schedule will always be running.

Hi @arieleeuw Thank you for your comment. Can you explain it a bit more? Isn't the scheduler supposed to let the instances run based on the period? In this case: 8 am to 6 pm mon to fri means instances are only allowed to run between 8-6 mon-fri and will be turned off.

I've tried removing the `override_status` field, waited for my Lambda to execute and my instances are still running.

**Comment by stevepop** [comment]
In my case, I don't even have that property set at all and still no dice getting the instances shutdown at the stipulated times.

**Comment by nguyendviet** [comment]
I confirm that removing the `override_status` works for me. My instances now can be stopped.
