### ISSUE TITLE
CloudWatch alarms thrown when UseCloudWatchMetrics is enabled

### ISSUE THREAD

**Issue by electric** [awslabs/aws-instance-scheduler#13]
Hi,

I'm getting the following alarms when UseCloudWatchMetrics is enabled with the default settings. Are there any other things I should be changing from the default configuration so that these are not raised?

ConsumedReadCapacityUnits < 66 for 15 datapoints within 15 minutes
ConsumedReadCapacityUnits < 165 for 15 datapoints within 15 minutes

**Comment by arieleeuw** [comment]
Hi, these messages are just to indicate that the capacity of the table is higher that the actual usage. Before DynamoDB autoscaling was introduced you could react to this event by reducing the r/w units for this table. This is all handled by DynamoDB that will reduce the capacity automatically.

**Comment by ankur-compro** [comment]
Hello All,

I am also getting similar alrm which says:

> ConsumedReadCapacityUnits < 360 for 15 datapoints within 15 minutes

Following are my Dynamo DB Table's Read & Write capacities.

Read Capacity: 12 ( With Autoscaling enabled, See attched screenshot)
Write Capacity:  12  ( With Autoscaling enabled,See attched screenshot)

Should I need to take any action at my end?

Thanks
Ankur
![capacity](https://user-images.githubusercontent.com/16202592/47771101-f59cbe80-dd07-11e8-8115-8c3b2fa0d561.png)

**Comment by arieleeuw** [comment]
These metrics are created by the CW Rules used by the autoscaling. Will investigate if there is a way to suppress the alarms that will not affect the working of the autoscaling.
Alarms do not have impact on working of Instance Scheduler

**Comment by behemphi** [comment]
While the alarms don't have an operational impact on the infrastructure, if I am going to use Cloudwatch as a monitoring and alerting tool, they become unwanted noise. This creates an operational impact on my humans :-)

Any news on this?  Any help to be offered from the user end?

Thanks for looking into it.

**Comment by arieleeuw** [comment]
Hi,
In our next update we will replace DynamoDB autoscaling by the new DynamoDB on demand provisioning so these alarms, and the unwanted noise,  are not longer there.

**Comment by shsenior** [comment]
Fixed in v1.2.0
