### ISSUE TITLE
pytz module error

### ISSUE THREAD

**Issue by sarangrao** [awslabs/aws-instance-scheduler#134]
The 1.2.0 version had a pytz folder under source. In version 1.3.0 this was removed but it is still used in the code.
I get the below error when trying to run the code
Unable to import module 'main': No module named 'pytz'

I tried installing the module using pip install pytz but this doesnt add it to the zip file while packaging.
Should I be packaging it in another way?

**Comment by tapughose** [comment]
Hi @sarangrao, 

can you please elaborate what types of command you are trying to run?

btw, if you are deploying the solution manually then you need to execute `build-s3-dist.sh` script from `deployment` directory. However, there is an [unnecessary line](https://github.com/awslabs/aws-instance-scheduler/blob/master/source/code/makefile#L57) in Makefile which you will have to remove before executing the script.

**Comment by georgebearden** [comment]
Hi @sarangrao - Please let us know if you are still having this issue after following the advice @tapughose gave. Thanks!
