### ISSUE TITLE
stack version confusion

### ISSUE THREAD

**Issue by include** [awslabs/aws-instance-scheduler#138]
Hi,

First and foremost thank you very much for releasing this very useful stack :)

Meanwhile, I am trying to figure what value to pass to `version` argument when running the `make` stack command. `make bucket=solutions-test-reference solution=aws-instance-scheduler version=1.2.1`

So,

- README.md shows `version=1.2.1`
- CHANGELOG.md says version `0.0.1`
- `source/code/version.txt` has `1.3.0`
- And finally (AFAIK) the last commit message says `Updated to v1.3 `.

What version should I use as reference?
Will future releases rely on one reference to this value? Perhaps only on `CHANGELOG.md`?

Thank you.

Cheers,
Francisco

**Comment by mohsenari** [comment]
Hi Francisco, thanks for finding out this issue and apologies for the confusion. The correct version number is 1.3.0 I'll add a note in our backlog to fix the inconsistency. The version number in README is purely an example. So I wouldn't treat that as a reference for version number. However, I will note that both README and CHANGELOG to be updated.

**Comment by include** [comment]
Hi @mohsenari great! thank you very much! Meanwhile I managed to deploy it without issues :)
