### ISSUE TITLE
EC2 Instances not Starting

### ISSUE THREAD

**Issue by korimus81** [awslabs/aws-instance-scheduler#139]
My instances stop correctly but will not start. I tried working with AWS support but they directed me here.  I deployed the cloud formation using pretty basic settings. Just selected my timezone really.  I then modified the existing "seattle-office-hours" schedule and "office-hours" period to test with.  I cannot even see the API call to start my instances.  Only stop works.

**Comment by arieleeuw** [comment]
Are you using encrypted volumes?

**Comment by korimus81** [comment]
Yes!

**Comment by arieleeuw** [comment]
Encrypted Amazon EBS Volumes

If your Amazon EC2 instances contain encrypted Amazon Elastic Block Store (Amazon EBS) volumes, you must grant the Instance Scheduler permission to use the customer master key (CMK) to start and stop instances. Add the kms:CreateGrant permission to the Instance Scheduler role (<stackname>-SchedulerRole-<id>).

**Comment by korimus81** [comment]
Oh man just found that! And now it works!! 

Thank you!

**Comment by DaveO-IRESS** [comment]
When the scheduler is missing the kms:CreateGrant permission and fails to start instances with encrypted volumes, they still get tagged with the 'started' tag; this is confusing. Is there any way to stop this happening? Or even a tag to say scheduler attempted and failed to start the instance?

**Comment by knihit** [comment]
It is wonderful that the solution is now working and the resolution provided above worked for you. May I request to change the status if the issue is resolved.

Thanks

**Comment by somersbd** [comment]
I'm having this same problem and would like some clarification on the fix?
I added the kms:CreateGrant permission to the SchedulerPolicy area but that does not appear to be the only thing needed?
The EBS volume is encryted but the key is in a different account does this other account key need to specified some where in the policy?

**Comment by easante817** [comment]
having the same problem
