### ISSUE TITLE
AWS Instance Scheduler Cross-account 

### ISSUE THREAD

**Issue by randpow** [awslabs/aws-instance-scheduler#14]
Hi,

i follow these steps to deploy the solution,
https://docs.aws.amazon.com/solutions/latest/instance-scheduler/deployment.html
and it works fine for the same account (AAAAAAAA) but when i try to extend the scheduler to a secondary account (BBBBBBBBBB) i always get the following error from Cloud Watch,

ERROR : Can not assume role arn:aws:iam::BBBBBBBBBB:role/EMCSTemp-EC2SchedulerCrossAccountRole-1A751JI9G9V1Y for account BBBBBBBBBB, (An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::AAAAAAAA:assumed-role/EMCSTemp-SchedulerRole-1ESJBRLZ26VKA/EMCSTemp-InstanceSchedulerMain is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::BBBBBBBBBB:role/EMCSTemp-EC2SchedulerCrossAccountRole-1A751JI9G9V1Y))

StackName: EMCSTemp

I also added this inline policy in the user's group:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1520691087000",
            "Effect": "Allow",
            "Action": [
                "sts:AssumeRole"
            ],
            "Resource": [
                "arn:aws:iam::BBBBBBBBBB:role/EMCSTemp-EC2SchedulerCrossAccountRole-1A751JI9G9V1Y","arn:aws:sts::AAAAAAAA:assumed-role/EMCSTemp-SchedulerRole-1ESJBRLZ26VKA/EMCSTemp-InstanceSchedulerMain"
            ]
        }
    ]
}

But still the same error. Any idea?

Thanks in advance.

Alberto

**Comment by arieleeuw** [comment]
Alberto,

In order to extend to another account:
-Login to that account 
-Create a stack in that account using this template **https://s3.amazonaws.com/solutions-reference/aws-instance-scheduler/latest/instance-scheduler-remote.template**
-Enter the number of the account in which the Scheduler is deployed
-The stack creates a cross account role that gives the Scheduler account permissions to make the required calls
-In the output from the stack locate the arn of the created role
-Log in to the scheduler account and update the scheduler stack, enter the arn of the cross account role in the list of accounts in which you want to scheduler instances

**Comment by randpow** [comment]
Thanks a lot. It works perfectly.

**Comment by randpow** [comment]
Hi,

in order to create periods and schedules i use dynamoDB console and some of them are working but the rest don't. I get the following warning in the CloudWatch logs:

2018-03-17 - 23:56:14.401 - WARNING : Skipping instance EC2:i-0487694xxxx33dbef (ServerEnterprise) in region eu-west-1 for account 7xxxxx09562, schedule name "esc-vertical" is unknown

Any idea whats is going on?

Thanks

**Comment by arieleeuw** [comment]
This means that the scheduler has found an instance with the tag you used for specifying the name of the schedule, but it can not find that schedule in the dynamodb configuration table. Make sure there is an entry of type schedule in the database with exactly that name. (case sensitive and beware of leading and training spaces)
A simple way to test is to the the scheduler-cli describe-schedules command that uses the same logic as the configuration reader of the scheduler.

**Comment by randpow** [comment]
Thank you for your response. Unfortunately, i am still having the same issue and the scheduler-cli describe function detetcts the entries,

{
   "Schedules": [
      {
         "Timezone": "Europe/Madrid",
         "Name": "demanda",
         "Type": "schedule",
         "Description": "Vertical scaling",
         "Periods": [
            "up@m5.xlarge",
            "down@m5.large"
         ]
      }

{
   "Periods": [
      {
         "Description": "Down hours",
         "Weekdays": [
            "mon-sun"
         ],
         "Begintime": "00:16",
         "Endtime": "06:15",
         "Type": "period",
         "Name": "down"
      }

 {
         "Description": "Up hours",
         "Weekdays": [
            "mon-sun"
         ],
         "Begintime": "06:16",
         "Endtime": "00:15",
         "Type": "period",
         "Name": "up"
      }

I also add the tag "Schedule = demanda" in the EC2 instance.

Thanks

**Comment by arieleeuw** [comment]
It might be the fact that in the up period the begintime > endtime which is not allowed (we do not support wrapping of times as this might conflict with the weekdays specifications). In the log stream you can see the message "stop_date must be equal or later than start_date" at the point  the scheduler loads the configuration and it skip the invalid period and the schedule it is used in. Normally these situations are caught by the CLI when you create the periods that uses the same code as the scheduler to check the schedule/period data.

you case you need 3 periods 
up1 -> 00:00-00:15
down -> 00:16-06:15
up2-> 06:16-23:59

The scheduler will stop/start the instances at 00:16 and 06:16 to resize it

If this schedule needs to run every day with the same times you can omit the weekdays as well.

**Comment by randpow** [comment]
Thanks again, that was the key. Using CLI everything works fine.

**Comment by randpow** [comment]
Hi arieleeuw ,
I've seen that you are also involved in AWS OpsAutomator solution. I succesfully deployed the solution and i also  a Create Snapshot Task but i can not find the snapshot. Where is locate it? i don't receive any error in CloudWatch logs, so i guess it is working fine.

Thnk you in advance.

Alberto.

**Comment by arieleeuw** [comment]
Snaphots are created in the account you are Ops Automator running or in the accounts for which you added cross account roles for in the task. You should see them in the EC2 console under snapshots. Make sure to tag the Instances correctly. The name of the tag is by default OpsAutomatorTaskList and the value should include the name of the task stack you created to configure your task.

**Comment by randpow** [comment]
Hi,

This is how i configured it,
And the task
I used the tag OpsAutomatorTaskList and value  CreateSnapshot but nothing
appear in the snapshot section.

Thanks

**Comment by arieleeuw** [comment]
Can you send me the the parameters and/or the configuration records for the task?
What is your cronies interval?

**Comment by randpow** [comment]
![3c88568e-0b01-42d8-ba21-e785e10fd936](https://user-images.githubusercontent.com/37248179/37801796-369a8cb2-2e28-11e8-9608-55655401c622.jpeg)
![4928450b-58e2-45c6-afc8-3751daa2cc44](https://user-images.githubusercontent.com/37248179/37801797-36c91050-2e28-11e8-9047-b7cd88240fa0.jpeg)

**Comment by arieleeuw** [comment]
There are multiple configuration errors.

The contact us not valid so the task will never execute.

https://en.m.wikipedia.org/wiki/Cron is an excellent reference on this.
If you want to run it every hour on 15 min past the hour use
15 * * *?
Every 15 minutes is
0/15 * * *?

In order to make snapshot you have to put the tag OpsAutomatorTaskList with a value of EMCOpsCreateSnapshot on the instance.

I also see the Task Enabled is set to No, this should be Yes

The snapshot tags parameter is used to put tags on the created snapshots, not for selecting instances

Hope this helps.



On 22 Mar 2018, at 23:25, randpow <notifications@github.com<mailto:notifications@github.com>> wrote:


[3c88568e-0b01-42d8-ba21-e785e10fd936]<https://user-images.githubusercontent.com/37248179/37801796-369a8cb2-2e28-11e8-9608-55655401c622.jpeg>
[4928450b-58e2-45c6-afc8-3751daa2cc44]<https://user-images.githubusercontent.com/37248179/37801797-36c91050-2e28-11e8-9047-b7cd88240fa0.jpeg>

**Comment by randpow** [comment]
Thanks again. Now is working, problem was the cron expresion and the tags.

Have a good weekend

**Comment by Toolazy2work** [comment]
So this thread came up with the google search for "schedule name "X" is unknown".  I solved the issue by using the correct form for timezone.  I was getting the error when using "America/New_York".  Im now using "US/Eastern" and it seems to be working.  I dont know if this helps you or not, but figured id respond with a positive result.

**Comment by arieleeuw** [comment]
Hi, 
Can you please check the original spelling of the timezone you used as this should be a valid timezone. For timezones we use the pytz module and according to this module this is a valid timezone name.

```
$ python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 12:39:47) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytz
>>> pytz.timezone("America/New_York")
<DstTzInfo 'America/New_York' LMT-1 day, 19:04:00 STD>
>>> 
```

**Comment by shsenior** [comment]
Closing due to time elapsed since last correspondence. Please re-open this if you are still having an issue.

**Comment by dms1981** [comment]
As an addendum to this, the cross account roles are referenced in DynamoDB in the ConfigTable created by the CloudFormation stack. You can see the references in `type/Partition Key = Config > cross_account_roles`.
