### ISSUE TITLE
RDS instance not stopping

### ISSUE THREAD

**Issue by fbalassiano** [awslabs/aws-instance-scheduler#144]
Hi,
I just added a new RDS instance to the scheduler, but the instance is not being stopped. In the log, we can see the following:
<img width="1533" alt="Screen Shot 2020-01-15 at 11 58 36 PM" src="https://user-images.githubusercontent.com/49492952/72558234-e6038a00-3867-11ea-9835-db5d3b5ddf45.png">

Other RDS instances using the same schedule are being stopped/started accordingly.
We have a cross-account implementation, so this is a new account I just added to the scheduler.
Any idea?
Thanks!

**Comment by lovepurohit** [comment]
Hi @fbalassiano 
It seems like it is a permission issue when deleting a snapshot. Kindly confirm whether you have required permission attach to the IAM role for deleting the snapshots.

**Comment by fbalassiano** [comment]
Hi @lovepurohit 
Yes, it was a permission issue. We have already solved it by adding the correct permissions.
Thanks anyway for the reply.
