### ISSUE TITLE
Using 2 periods in a schedule doesnt stop EC2 instance

### ISSUE THREAD

**Issue by rcarl80** [awslabs/aws-instance-scheduler#145]
I'm trying to stop an instance next day at 12:30am.  But the scheduler doesnt seem to want to stop the instance.

I have 2 periods
Period 1
begintime @ 0600

Period 2
endtime @ 00:30

Supposedly based on the information it should stop the instance based on the endtime in the 2nd period, but just seems to set the desired state to "running" and doesnt stop the instance.

**Comment by arieleeuw** [comment]
For period 1 add an endtime of 23:59.
For period 2 add a starttime of 00:00

as the scheduler will recognize the adjacent periods it will keep the instance running at the end of period 1

**Comment by rcarl80** [comment]
Thanks i will give this a test, and confirm if it works.
