### ISSUE TITLE
botocore bad practice

### ISSUE THREAD

**Issue by gustavo-eduard** [awslabs/aws-instance-scheduler#146]
May instance scheduler package together requests lib in future versions?

I really like the way that instance scheduler uses many services of AWS. For new users that simple want to schedule resources it´s a soft way to present in practice new AWS services like DynamoDB and Lambda.

botocore.vendored.requests should be replaced by a official and public lambda layer. It would be a gracefully way to present this lambda layers too as dynamodb, cloudformation and lambda themself.

Still thinking in beginner user, install the request package directly will result in a poor experience for them, whereas code will not show up in console, because the code will be weightier than 10mb

https://github.com/awslabs/aws-instance-scheduler/blob/6f86b91fd641a2526c4c0b1c78245e41f3406efb/source/code/util/metrics.py#L18
https://github.com/awslabs/aws-instance-scheduler/blob/6f86b91fd641a2526c4c0b1c78245e41f3406efb/source/code/util/custom_resource.py#L18

**Comment by ericquinones** [comment]
Hi @gustavo-eduard 
Thank you for the note. We will be updating the solution to remove the dependency on the vendored requests module in botocore. Please keep an eye on this repository for updates

**Comment by chaitand28** [comment]
This issue has been fixed in the release 1.3.1. Please deploy the latest template to get the updated code.
