### ISSUE TITLE
RDS scheduler not working, error - local variable 'snapshot_name' referenced before assignment

### ISSUE THREAD

**Issue by ziyadmhd** [awslabs/aws-instance-scheduler#154]
ERROR : Error stopping rds instance RDS:myrdsinstance (myrdsinstance), (local variable 'snapshot_name' referenced before assignment)

**Comment by dscpinheiro** [comment]
Hi @ziyadmhd,

Sorry for the inconvenience. Could you answer these questions to help us troubleshoot the problem?

- What version of the solution are you running? This can be checked by looking at the template. For instance, if you see this section "S3Key": "aws-instance-scheduler/v1.3.0/instance-scheduler.zip", it means you're running v1.3.0

- Is this happening for every database or one specific instance?

- Every log is written to a log group named _instance-scheduler-logs_. If you query this group (using Logs Insights like the example below) filtering by the timestamp where the problem happens, do you see any other ERROR messages?

![Screen Shot 2020-02-26 at 11 03 02 AM](https://user-images.githubusercontent.com/3842788/75367989-04be5d00-58b9-11ea-8c84-17b0b2429659.png)

**Comment by ziyadmhd** [comment]
1) we are running version 1.2.0
2) It is not happening in every accounts. only in few.
3) i don't see any other messages related to this error.

**Comment by ziyadmhd** [comment]
Hi,
Can you please suggest here.
