### ISSUE TITLE
hibernate true gives rollback in cloudformation

### ISSUE THREAD

**Issue by 1robroos** [awslabs/aws-instance-scheduler#158]
Hello,
 I am trying to add "Hibernate": "True" into the Schedule definition, but the template is being rolled back with the status reason:`Failed to update resource`
My schedule looks like:
```
{
    "AWSTemplateFormatVersion": "2010-09-09",
    "Metadata": {
        "AWS::CloudFormation::Designer": {}
    },
    "Resources": {
        "DutchOfficehours": {
            "Type": "Custom::ServiceInstanceSchedule",
            "Properties": {
                "Name": "NL-OfficeHours",
                "NoStackPrefix": "True",
                "Description": "Office hours in NL",
                "ServiceToken": "arn:aws:lambda:eu-central-1:[xxxxxxxxxxxx]:function:myVPC-NightShiftScheduler-InstanceSchedulerMain",
                "Enforced": "True",
                "Timezone": "Europe/Amsterdam",
                "Periods": [
                    {
                        "Description": "Opening hours on weekdays",
                        "BeginTime": "08:00",
                        "EndTime": "18:00",
                        "WeekDays": "Mon-Fri"
                    },
                    {
                        "Description": "Opening hours in weekend",
                        "BeginTime": "09:00",
                        "EndTime": "17:00",
                        "WeekDays": "Sat-Sun"
                    }
                ]
            }
        }
    }
}
``` 

Can you guide me what is wrong ? I tried to add it after "Enforced": "True".

**Comment by lovepurohit** [comment]
Hi @1robroos,

If it does not work from the CloudFormation template, you can directly go and update the already created schedule in the dynamo DB and the instance scheduler will pick them up.

Thank you

**Comment by gockle** [comment]
@1robroos Has the issue been resolved?

**Comment by 1robroos** [comment]
Thanks.
At this moment I  discovered I do not have a use case for hibernation (only have t3 instances where hibernation is not supported, also Windows instances that do not meet the hibernate requirements ) so this is where it stops for me now.
And if I would have an instance that fulfills the requirements for hibernation, then I would be reluctant changing the schedule in DynamoDB directly. 
Thanks for your help.
