### ISSUE TITLE
TimeZone is not consistent throughout the application

### ISSUE THREAD

**Issue by billtfreeman** [awslabs/aws-instance-scheduler#162]
I have a schedule that starts Monday at 2am EST for development servers that are off on the weekend.
It looks like a portion of the code is using the configured Eastern timezone but what the schedule is checking against for current time is UTC.

Example:  2020-04-20 - 03:30:25.275 - DEBUG   : [stopped] Weekday "sun" not in weekdays (mon-fri)
2020-04-20 - 03:30:25.275 is Eastern TZ on Monday but like the above states-in UTC it's still Sunday.

Here is one of the conflicting statements.
Example: 2020-04-20 - 06:00:24.284 - DEBUG   : Time used to determine desired for instance is Mon Apr 20 02:00:21 2020

I saw other issues about display items but this is functionality.  The workaround is just to change all my schedules to UTC time which I am in the process of.  But then I need to ask, what is the purpose of setting a timezone?

**Comment by gockle** [comment]
Instance scheduler has timezone configuration available in two places one is in the generic default timezone field (refer config entry in the dynamodb table), the other is the timezone information can be specified for a specific schedule,
 
Sample (Response is from scheduler-cli)
 
     {
         "Timezone": "UTC",
         "Description": "Vertical scaling on weekdays, based on UTC time",
         "Periods": [
            "working-days@t2.micro",
            "weekends@t2.nano"
         ],
         "Name": "scale-up-down",
         "Type": "schedule"
      },
Can you confirm if the timezone is reflecting the desired value in both fields, timezone can be empty in the schedule information the code should default to the ‘default timezone’ field.

**Comment by billtfreeman** [comment]
I could not test this since it was causing issues, just used UTC instead of EST.

My deployment method was to update cf template and use the cloudformation parameter for default_timezone and set to EST
.
I did not have any other values in the timezone columns (except for the default "scale-up-down" that you pointed out which we are not using.  
To go back to using EST, I can probably specify the timezone (EST) on each row of the schedule.  Thanks for pointing out this option.

**Comment by maykays** [comment]
Adding this issue to our roadmap backlog. Please up-vote if you want this feature. Do not submit a new feature request.

**Comment by githubnoobieme** [comment]
upvote

**Comment by rgoltz** [comment]
+1

**Comment by marcelomanchester** [comment]
upvote

**Comment by maykays** [comment]
shipped in v1.4
