### ISSUE TITLE
The tool has been working fine for a year now, but the lambda's cost skyrocketed in the last few months.  

### ISSUE THREAD

**Issue by jcyriac-synamedia** [awslabs/aws-instance-scheduler#164]
Thanks for creating this great tool. We have been using it for a year now. We have hosted this centrally, and 15 accounts are configured with cross account access to use this tool. We have also enabled it for 10 regions. 

However, for some reason, the lambda cost for our central account has skyrocketed over the last 2 months. The bill was $330 last month for lambda. It was only around ~$40 till Dec last year. 

![image](https://user-images.githubusercontent.com/53347490/81447511-a8a76d00-9174-11ea-863f-7b139d2d5b1f.png)
![image](https://user-images.githubusercontent.com/53347490/81447603-dd1b2900-9174-11ea-989a-bd4bbfa0825d.png)

It had scheduler frequency of 10 minutes, and memory of 1024mb. I have done some resizing and hoping that the lambda's bill will be lower this month.

Here is the updated configuration we have, 
![image](https://user-images.githubusercontent.com/53347490/81447982-83ffc500-9175-11ea-9be7-e2fef80e7d3f.png)

Let us know if this configuration is sufficient when you have 15 accounts and 10 regions. Please also share your thoughts on this unexpected bill for lambda. 

Thanks

**Comment by deolank** [comment]
Hi,

We are currently looking into this issue. Can you provide more information about the Schedule that you are using for your instances.

Thanks.

**Comment by jcyriac-synamedia** [comment]
![image](https://user-images.githubusercontent.com/53347490/82437251-000bde00-9a8f-11ea-9787-291b5b1c8f03.png)
we have quite a lot of schedules defined. 15 accounts are connected to this, so not sure which ones are actually in use.

**Comment by jcyriac-synamedia** [comment]
i increased the memory to 1024 mb few months back . that caused the spike in bill i think. 

it runs every 10 mins. so 6*24*30 = 4320 execution a month. 

there is significant difference in lambda pricing when 1024 mb used. 
![image](https://user-images.githubusercontent.com/53347490/82437497-6690fc00-9a8f-11ea-8ba8-f49bc95eefd7.png)

**Comment by jcyriac-synamedia** [comment]
so we have went back 128 mb .. the question is, would 128mb be sufficient when running it for 10 regions, across 15 accounts?

**Comment by deolank** [comment]
are you using any maintenance windows for these schedules?

**Comment by jcyriac-synamedia** [comment]
no .. dont think so.

**Comment by jcyriac-synamedia** [comment]
![image](https://user-images.githubusercontent.com/53347490/85296099-c7e62980-b498-11ea-8b98-b740b5147256.png)

bill is down to 17$ this month so far. 
![image](https://user-images.githubusercontent.com/53347490/85296175-e4826180-b498-11ea-8223-dd34f7b0cd84.png)
these are the settings we have. 

went back to 128 mb .. and changed interval from 10 to 30.
