### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by gcormier** [awslabs/aws-instance-scheduler#17]
Documentation seems to be severely lacking given the number of options this thing has.

I far prefer the old version as I can get it up and running in 5 minutes.

**Comment by arieleeuw** [comment]
Hi,

Can you give an indication on you think what is missing in the documentation so we can pass that to our technical writers to improve it?

**Comment by gcormier** [comment]
Just took another look. So the info is there, but it was not where I expected to see it when I wanted to jump in.

I instantly made my way to this first page : https://docs.aws.amazon.com/solutions/latest/instance-scheduler/deployment.html

This got my solution going. However, steps 2 and 3 were where I got frustrated. It talks about setting these up, but does not refer to any details on the values. There should be links for details on periods and schedules to Schedules and Periods ( https://docs.aws.amazon.com/solutions/latest/instance-scheduler/components.html )

Schedules & Components might be better broken down as sub sections so they at least appear at a glance on the left pane. 

![image](https://user-images.githubusercontent.com/8388983/38365848-e18abc40-38ab-11e8-9e86-cca2e1163e51.png)

**Comment by arieleeuw** [comment]
Thanks for this feedback, I'll forward it to our technical writers. 
As part of the installation we also create a few sample schedules/periods that might help you to get going.

**Comment by gcormier** [comment]
I did see those, but didn't find they were enough - wanted the juicy details :)

**Comment by gcormier** [comment]
Additionally, the period value documentation does not specify what happens if certain fields are empty - weekdays, monthdays,etc.

(It is specified for starttime/stoptime)

**Comment by shsenior** [comment]
Closing due to time elapsed since last correspondence. Please re-open this if you are still having an issue.
