### ISSUE TITLE
DynamoDB - Instance-Scheduler-ConfigTable - Not refreshing

### ISSUE THREAD

**Issue by mchennamsetty** [awslabs/aws-instance-scheduler#171]
Updated the Instance-Scheduler-ConfigTable table with new schedule and period. But the lambda is not pulling the latest data from Dynamo DB. Anything i need to do to invalidate any cache. Appreciate your help.

**Comment by praveenis** [comment]
Hi @mchennamsetty ,
Adding new schedule and period to the ConfigTable will be picked up automatically by the lambda. Can you please share below details for further investigation.

1. Error logs (if any)
2. Newly added schedule and period item from ConfigTable.
3. is this working previously?
4. Parameter from Instance Scheduler stack
5. Region where you tagged EC2 instance

Thanks,
Praveen

**Comment by eryon** [comment]
@praveenis this is happening for me too. It's my first attempt.

I found a `warning` in the scheduler logs:
```
WARNING : Skipping instance EC2:i-04086[hidden] (sandrabot) in region us-west-2 for account [hidden], schedule name "sandrabot-gametime" is unknown
```
In the CloudWatch handler logs, I found this error:
```
ERROR : "tue-wed-sat" is an unknown value
```

The schedule is configured as:
```json
{
  "description": {
    "S": "Sandrabot gametime"
  },
  "name": {
    "S": "sandrabot-gametime"
  },
  "periods": {
    "SS": [
      "sandrabot"
    ]
  },
  "timezone": {
    "S": "US/Pacific"
  },
  "type": {
    "S": "schedule"
  }
}
```
and the period is defined as:
```json
{
  "begintime": {
    "S": "10:00"
  },
  "endtime": {
    "S": "22:00"
  },
  "name": {
    "S": "sandrabot"
  },
  "type": {
    "S": "period"
  },
  "weekdays": {
    "SS": [
      "tue-wed-sat"
    ]
  }
}
```

This is the instance, in `us-west-2`
![image](https://user-images.githubusercontent.com/13526140/89950356-5300b780-dbde-11ea-9c92-d592488de36c.png)

**Comment by praveenis** [comment]
Hi @eryon , issue is with the weekdays value in period. try the period like this.

To run scheduler from tue to sat.

{
  "begintime": {
    "S": "10:00"
  },
  "endtime": {
    "S": "22:00"
  },
  "name": {
    "S": "sandrabot"
  },
  "type": {
    "S": "period"
  },
  "weekdays": {
    "SS": [
      "tue-sat"
    ]
  }
}

To run only on tue, wed and sat.
{
  "begintime": {
    "S": "10:00"
  },
  "endtime": {
    "S": "22:00"
  },
  "name": {
    "S": "sandrabot"
  },
  "type": {
    "S": "period"
  },
  "weekdays": {
    "SS": [
      "tue,wed,sat",
    ]
  }
}

Thanks,
Praveen

**Comment by eryon** [comment]
@praveenis thanks, you're right. Correcting that piece fixed the whole config 🎉
