### ISSUE TITLE
New schedule with mon start 800 and stop fri 1800 not working 

### ISSUE THREAD

**Issue by acloud-developer** [awslabs/aws-instance-scheduler#175]
Created two period  
mon-start-0800. ( to start instance on Monday 800 hrs ) and  fri-stop-1800 (to stop at friday 1800hrs ).

the created schedule 'mon-start-0800-fri-stop-1800'

Instance is starting at Mon  800 but stopping at Tue 12:01AM. After this instance never restarts it self. Looks like lambda is not picking up latest schedule

**Comment by praveenis** [comment]
Hi @acloud-developer,

Can you please create one more period in between to run continuously for weekdays ('tue-thu'). Can you please refer this example https://docs.aws.amazon.com/solutions/latest/instance-scheduler/appendix-e.html

Thanks,
Praveen
