### ISSUE TITLE
Instances are not starting/stopping on multiaccount env using centrilized CMK

### ISSUE THREAD

**Issue by KenkoGeek** [awslabs/aws-instance-scheduler#178]
Hi, 

I'm using this solution on a multi-account environment using control tower, I describe the deployment and conditions:

- InstanceScheduler its deployed on Shared Account
- CMK for EBS encryption are on Audit account
- EC2/RDS are on child accounts using CMK from Audit account

But EC2 and RDS are not starting/stopping, I assume that maybe it's a KMS permission

I added InstanceSheduler role on CMK policy for EC2 as follow:

> {
>     "Version": "2012-10-17",
>     "Id": "CMK-kms-keypolicy",
>     "Statement": [
>         {
>             "Sid": "Enable IAM User Permissions",
>             "Effect": "Allow",
>             "Principal": {
>                 "AWS": "arn:aws:iam::AUDITACCOUNT:root"
>             },
>             "Action": "kms:*",
>             "Resource": "*"
>         },
>         {
>             "Sid": "Allow access for Key Administrators",
>             "Effect": "Allow",
>             "Principal": {
>                 "AWS": "arn:aws:iam::AUDITACCOUNT:role/aws-reserved/sso.amazonaws.com/AWSReservedSSO_AWSAdministratorAccess_XXXXXXXXX"
>             },
>             "Action": [
>                 "kms:Create*",
>                 "kms:Describe*",
>                 "kms:Enable*",
>                 "kms:List*",
>                 "kms:Put*",
>                 "kms:Update*",
>                 "kms:Revoke*",
>                 "kms:Disable*",
>                 "kms:Get*",
>                 "kms:Delete*",
>                 "kms:TagResource",
>                 "kms:UntagResource",
>                 "kms:ScheduleKeyDeletion",
>                 "kms:CancelKeyDeletion"
>             ],
>             "Resource": "*"
>         },
>         {
>             "Sid": "Allow use of the key",
>             "Effect": "Allow",
>             "Principal": {
>                 "AWS": "arn:aws:iam::SHAREDACCOUNT:root"
>             },
>             "Action": [
>                 "kms:Encrypt",
>                 "kms:Decrypt",
>                 "kms:ReEncrypt*",
>                 "kms:GenerateDataKey*",
>                 "kms:DescribeKey"
>             ],
>             "Resource": "*"
>         },
>         {
>             "Sid": "Allow attachment of persistent resources",
>             "Effect": "Allow",
>             "Principal": {
>                 "AWS": [
>                     "arn:aws:iam::SHAREDACCOUNT:root",
>                     "arn:aws:iam::SHAREDACCOUNT:role/MyInstancesScheduler-SchedulerRole-XXXXX"
>                 ]
>             },
>             "Action": [
>                 "kms:CreateGrant",
>                 "kms:ListGrants",
>                 "kms:RevokeGrant"
>             ],
>             "Resource": "*"
>         }
>     ]
> }
> 

on CMK policy for RDS:

> {
>     "Version": "2012-10-17",
>     "Id": "CMK-kms-keypolicy",
>     "Statement": [
>         {
>             "Sid": "Enable IAM User Permissions",
>             "Effect": "Allow",
>             "Principal": {
>                 "AWS": "arn:aws:iam::AUDITACCOUNT:root"
>             },
>             "Action": "kms:*",
>             "Resource": "*"
>         },
>         {
>             "Sid": "Allow access for Key Administrators",
>             "Effect": "Allow",
>             "Principal": {
>                 "AWS": [
>                     "arn:aws:iam::AUDITACCOUNT:role/aws-reserved/sso.amazonaws.com/AWSReservedSSO_AWSAdministratorAccess_XXXXX"
>                 ]
>             },
>             "Action": [
>                 "kms:Create*",
>                 "kms:Describe*",
>                 "kms:Enable*",
>                 "kms:List*",
>                 "kms:Put*",
>                 "kms:Update*",
>                 "kms:Revoke*",
>                 "kms:Disable*",
>                 "kms:Get*",
>                 "kms:Delete*",
>                 "kms:TagResource",
>                 "kms:UntagResource",
>                 "kms:ScheduleKeyDeletion",
>                 "kms:CancelKeyDeletion"
>             ],
>             "Resource": "*"
>         },
>         {
>             "Sid": "Allow use of the key",
>             "Effect": "Allow",
>             "Principal": {
>                 "AWS": [
>                     "arn:aws:iam::SHAREDACCOUNT:root",
>                     "arn:aws:iam::SHAREDACCOUNT:role/MyInstancesScheduler-SchedulerRole-XXXXXX"]
>             },
>             "Action": [
>                 "kms:CreateGrant",
>                 "kms:Encrypt",
>                 "kms:Decrypt",
>                 "kms:ReEncrypt*",
>                 "kms:GenerateDataKey*",
>                 "kms:DescribeKey"
>             ],
>             "Resource": "*"
>         },
>         {
>             "Sid": "Allow attachment of persistent resources",
>             "Effect": "Allow",
>             "Principal": {
>                 "AWS": "arn:aws:iam::SHAREDACCOUNT:root"
>             },
>             "Action": [
>                 "kms:CreateGrant",
>                 "kms:ListGrants",
>                 "kms:RevokeGrant"
>             ],
>             "Resource": "*",
>             "Condition": {
>                 "StringEquals": {
>                     "kms:ViaService": "rds.us-east-1.amazonaws.com",
>                     "kms:CallerAccount": "SHAREDACCOUNT"
>                 }
>             }
>         }
>     ]
> }

Can you please tell me if EC2 Scheduler works fine under these conditions?

**Comment by groverlalit** [comment]
@KenkoGeek Thanks for reaching out to us. Please confirm if you have updated instance scheduler role with the IAM policy that is needed to access the CMK in your AUDIT account? Example below.

We would also recommend that if only limited IAM resources need access this CMK, you can safely remove the root ARN for the 'SHAREDACCOUNT' account and only use role ARNs. If root ARN exists in the key policy, then specific role ARN is probably redundant.

Example:
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "Allow Use Of CMK In AUDIT Account ",
      "Effect": "Allow",
      "Action": [
        "kms:Encrypt",
        "kms:Decrypt",
        "kms:ReEncrypt*",
        "kms:GenerateDataKey*",
        "kms:DescribeKey"
      ],
      "Resource": "arn:aws:kms:us-west-2:AUDITACCOUNT:key/1234abcd-12ab-34cd-56ef-1234567890ab"
    }
  ]
}

Hope this helps. Thanks.
For more information please refer to: https://docs.aws.amazon.com/kms/latest/developerguide/key-policy-modifying-external-accounts.html

**Comment by KenkoGeek** [comment]
Hi @groverlalit thank you for the answer,

Actually the EC2 instances are stopping but not starting with the following error "Client.InternalError: Client error on launch" "Server.InternalError"

RDS instances/clusters are starting/stopping just fine.

I add the following section on lambda role policy:

>         {
>             "Action": [
>                 "kms:Encrypt",
>                 "kms:Decrypt",
>                 "kms:ReEncrypt*",
>                 "kms:GenerateDataKey*",
>                 "kms:DescribeKey",
>                 "kms:CreateGrant"
>             ],
>             "Resource": [
>                 "arn:aws:kms:us-east-1:123456789012:key/fcda1806-9bea-42e5-996e-9d599197xxxx",
>                 "arn:aws:kms:us-east-1:123456789012:key/0a9cc313-c532-497f-8828-ea7e53b5xxxx",
>                 "arn:aws:kms:us-east-1:123456789012:key/11cb633d-96dd-4f77-b2c6-ea679503xxxx",
>                 "arn:aws:kms:us-east-1:123456789012:key/28995cbe-6f24-4eb5-85e8-9be625f7xxxx",
>                 "arn:aws:kms:us-east-1:123456789012:key/98f24975-e154-42fe-947d-11e5392bxxxx",
>                 "arn:aws:kms:us-east-1:123456789012:key/a67974c0-3df9-481e-9596-dfc07220xxxx",
>                 "arn:aws:kms:us-east-1:123456789012:key/658b7965-b2de-497c-abfd-afb7e2c9xxxx",
>                 "arn:aws:kms:us-east-1:123456789012:key/26b84333-a87d-4ea1-9d7c-023e6655xxxx"
>             ],
>             "Effect": "Allow"
>         }

For CMK policy I add the following section (EC2):

>         {
>             "Sid": "Allow scheduler role",
>             "Effect": "Allow",
>             "Principal": {
>                 "AWS": "arn:aws:iam::123456789012:role/InstancesSchedulerRole-1TCBT3IRSAUY5"
>             },
>             "Action": [
>                 "kms:CreateGrant",
>                 "kms:ListGrants",
>                 "kms:RevokeGrant",
>                 "kms:Encrypt",
>                 "kms:Decrypt"
>             ],
>             "Resource": "*"
>         }

**Comment by KenkoGeek** [comment]
Hi, the issue was solved,

Please be more specific on the documentation where you should add permissions over KMS if EBS is encrypted. 

You only specify `kms:CreateGrant` over the key on the main lambda role but this isn't enough.

CMK key must have:

```
{
       "Sid": "Allow scheduler role",
       "Effect": "Allow",
       "Principal": {
             "AWS": "arn:aws:iam::123456789012:role/InstancesSchedulerRole-1TCBT3IRSAUY5"
        },
        "Action": [
            "kms:CreateGrant",
           "kms:List*",
           "kms:DescribeKey",
           "kms:Encrypt",
           "kms:Decrypt"
       ],
           "Resource": "*"
 }
```
Then every role deployed (main account and child accounts) must have on the policy this:

```
    {
         "Effect": "Allow",
        "Action": [
           "kms:CreateGrant",
           "kms:List*",
           "kms:DescribeKey",
           "kms:Encrypt",
           "kms:Decrypt"
         ],
         "Resource": [
                       "*"
         ]
 }
```
NOTE: if you want to be more restricted on the role policy you can specify the KMS ARN on the resource section.
