### ISSUE TITLE
Auto-Tagging Instances Upon Creation

### ISSUE THREAD

**Issue by dyn0m1ght** [awslabs/aws-instance-scheduler#186]
In my environment, when an EC2 instance is launched, I use a lambda that utilizes EventBridges to notify the lambda to auto-tag EC2 and RDS instances with a schedule tag upon launch.

However, when an instance is launched outside of the schedule, say 0400, and I have a schedule that is 0500-1700 that is automatically tagged on the instance.  The instance is launched and started, schedule tag applied, however, the instance scheduler automatically stops the instance outside of the schedule when the expected behavior was for it to keep running until the end of the schedule and stop then.

I have stop_new_instances=None in the instance_scheduler.py so I figured it would just bypass those newly launched instances. 

Do you guys have any workarounds or am I missing something in the configuration?

 Thanks for all your help, otherwise the solution has been very helpful.

**Comment by praveenis** [comment]
Hi @dyn0m1ght , To stop an instance the first time it is tagged if it is running outside of the running period “stop_new_instances” flag must set to false. By default, this field is set to true. If this flag is not working, Can you please check if you are using instance scheduler version 1.3.2 and also share us the schedule used from dynamoDB.

Thanks,
Praveen

**Comment by dyn0m1ght** [comment]
Thank you, Praveen.  The desired behavior for me is for the instance to continue running through the first period after it is first launched.  However, it is stopped by the instance scheduler after is tagged with the schedule tag immediately after it is launched and the instance scheduler lambda runs.

The stop_new_instances is currently set to "None" which is the default condition that the development team set it to.

Here is the period
![image](https://user-images.githubusercontent.com/1565901/88547796-34020300-cfec-11ea-914b-91baf46550cd.png)

Here is the schedule:
![image](https://user-images.githubusercontent.com/1565901/88547842-44b27900-cfec-11ea-8092-67049ae1ba26.png)

I am currently utilizing version 1.3.1 of the instance scheduler.

Thanks!

**Comment by dyn0m1ght** [comment]
Hi, just curious is there a way to accomplish the above inherently in the scheduler or do I need to write the code to do it myself?

**Comment by praveenis** [comment]
Hi @dyn0m1ght , Can you please confirm 'stop_new_instances' boolean flag is set to 'false' in your schedule in DynamoDB. 

Thanks,
Praveen

**Comment by dyn0m1ght** [comment]
Hi @praveenis , that's the exact parameter I was looking for.  Thank you, I should have noticed that in the deployment guide under scheduler cli information.
