### ISSUE TITLE
overlapping periods

### ISSUE THREAD

**Issue by mdbratcher** [awslabs/aws-instance-scheduler#190]
We have some instance schedules with multiple periods.  My question is if you have overlapping periods with different shutdown times how does this play out.  Example: the schedule has a period #1 with start of 7am and shutdown at 7pm.  The same schedule has a another period #2 with the start up time of 6pm and 11pm.  Can the instances with this schedule tag that contains both periods stay up from 7am to 11pm without shutting down at 7pm because of first period shutdown time.
Thanks

**Comment by praveenis** [comment]
Hi @mdbratcher , Yes. Instances will be up from 7am to 11pm without shutting down since the periods are overlapping.
Thanks,
Praveen

**Comment by mdbratcher** [comment]
thanks
