### ISSUE TITLE
Throttling exception using ssm maintenance window

### ISSUE THREAD

**Issue by suttph01** [awslabs/aws-instance-scheduler#191]
I am supporting an account with a large number of EC2 instances across multiple regions.  The Instance scheduler is located in a single region, supporting itself & all other regions (4 in total).  The schedules are configured to use the SSM maintenance window ( weekly event on saturday mornings).
The scheduler logs are reporting frequent ThrottlingException errors, e.g.
_ERROR   : Caught Exception while getting the maintenance window: An error occurred (ThrottlingException) when calling the DescribeMaintenanceWindows operation (reached max retries: 4): Rate exceeded_
This appears to be causing the instances started for the maintenance window to stop frequently during the window.
Can the scheduler be updated to include a 'back-off' routine to prevent this?

**Comment by maykays** [comment]
We recommend you update to v1.3.3 (or v1.3.2 at a minimum.) v1.3.2 contains a fix related to the SSM feature (change log notes below). This fix is carried over into the CDK v1.3.3.
 
1.3.2 - 2020-06-22
*Fix the issue to start instances before the SSM maintenance window beings #101
***Updated the SSM feature to reduce lambda cost**
*Added HIBERNATE to the list of valid schedule properties

**Comment by zbornstein** [comment]
Does the new version of the scheduler 1.3.3 support retry backoff for EC2 and RDS scheduling? We see issues not related to SSM, but general API limits in our accounts.

**Comment by maykays** [comment]
Fix shipped in v1.4
