### ISSUE TITLE
AWS schedule causes improper shutdown of EC2 w/ MSSQL

### ISSUE THREAD

**Issue by NestorTangkeko** [awslabs/aws-instance-scheduler#192]
Hi, 

I’m not sure if it is bug or something else.  I’ve already configured the AWS Instance Scheduler and it's working fine. The issue is 
happens with the EC2 w/ MSSQL installed.  The AWS Instance Scheduler cause the OS to be improperly shutdown, if the EC2 instance has a MSSQL Server installed on it.  Once it boots up again, I see a Windows 2016 notification about it, like that of the attached file .  I do not experience this behavior on Windows 2016 without MSSQL Server installed.  Maybe you have an advise on how to resolve it.

As an addition info, I did the following troubleshooting, to see if it is really caused by the AWS Instance scheduler. Both did not produce the screen capture below.

1) Shutdown the Windows via remote desktop to the Server, then boot it up again.
2) “Stop” the EC2 instance via the EC2 console, then boot it up again.

![image](https://user-images.githubusercontent.com/59858781/89753273-2c714c80-db0a-11ea-9528-c384dc82524a.png)

**Comment by jgardsentry** [comment]
How long did it take the instance to shut down when you issued "Stop" to EC2?  There's likely a timer in this solution that issues a "forceful stop" after a certain period.

**Comment by NestorTangkeko** [comment]
> How long did it take the instance to shut down when you issued "Stop" to EC2? There's likely a timer in this solution that issues a "forceful stop" after a certain period.

I'm sorry but I don't monitor the scheduled shutdowns.  I just noticed it due to the startup and that improper prompt of Windows 2016 server.  Take note that it does not happen on EC2s without MS SQL server 2016.

**Comment by NestorTangkeko** [comment]
> @NestorTangkeko Potential bug; attempting to reproduce the issue.

I was told it could be the AWS Instance scheduler version?  I'm using version 1.2 still.  I just saw that the latest version is 1.3.2.

**Comment by NestorTangkeko** [comment]
Just an update.  I've installed the AWS Instance scheduler version 1.3.2 on another region, and the experience is the same.

I now believe that @jgardsentry is correct about the "forceful stop".  Is there a way to increase the wait-time, before resorting to a "force shutdown"?

Thank you.

**Comment by gockle** [comment]
@NestorTangkeko Can you try increasing the wait time using the lambda environment variable BOTO_RETRY, from the default **5, 10, 30, 0.25,** to the desired wait time? Following is the value and description for each entry, 
```
Default Wait time in seconds = 5
Default incremental wait time in seconds = 5
Default maximum wait time = 20
Default random factor = 0.25
```
Let us know if this addresses the issue with the "force shutdown" by delaying it to the default maximum wait time.

**Comment by NestorTangkeko** [comment]
@gockle .  I've set the value of BOTO_RETRY from 5,10,**30**,0.25 to 5,10,**300**,0.25, & the experience was the same.  Should I increase it further?

**Comment by gockle** [comment]
@NestorTangkeko Once you increase the value and save the environment variable change it should be enough, Ideally the maximum timeout value should be in range of what you are experiencing when you manually try to shut down the EC2 instance, if that is not resolving the issue, we will look into the issue and try to replicate it.

**Comment by NestorTangkeko** [comment]
@gockle , I've increased it to 900, and it still does not work.  Is there a maximum value for it?

![image](https://user-images.githubusercontent.com/59858781/92873207-613e2f80-f439-11ea-872b-2782e0070f92.png)

**Comment by gockle** [comment]
@NestorTangkeko There is no maximum value for the timeout, although I am currently trying to recreate the issue. Will get back once I have some information on this issue.

**Comment by gockle** [comment]
@NestorTangkeko I tried to replicate the issue by installing a MySQL Server in a windows instance, EC2 instance details are t2.large, us-east-1, 

Steps:
* Installed mysql Server 8.0 
* Initialized the data directory
* Started the server (Did not create any schema and tables). 
* Scheduled the aws-instance-scheduler to stop the server. 
* Verified if the if the "improper shutdown" message is being displayed by manually starting the server from the EC2 console. 
* No errors were displayed. 

Can you verify the steps and confirm or let me know if I am missing any steps?

**Comment by NestorTangkeko** [comment]
@gockle,

I believe you used MySQL instead of Microsoft's SQL.  I'm using MS-SQL.

**Comment by gockle** [comment]
@NestorTangkeko Will correct that and test the scenario again.

**Comment by gockle** [comment]
@NestorTangkeko I tried using the standard Windows with SQL Server 2016 EC2 instance (t3a.xlarge type), and could not replicate the issue. The system was shutting down and restarting (manually) without any warnings.

**Comment by NestorTangkeko** [comment]
@gockle , appreciate the support.  I'll experiment on my side.  Maybe its an OS issue, and nothing to do with AWS.

Thanks again

**Comment by gockle** [comment]
@NestorTangkeko Sorry could not recreate the issue on my end, there have been some changes to the Windows EC2 instances, Hibernate feature has been enabled for Windows instances more details [here](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/Hibernate.html).  Can you try using hibernate feature and see if that resolves the issue you are facing? Further details for enabling hibernate feature in the aws-instance-scheduler can be found [Implementation Guide](https://docs.aws.amazon.com/solutions/latest/instance-scheduler/components.html), the documentation mentions that is feature is only available for Linux instances but that is outdated information, we will update that documentation to rectify that.

**Comment by NestorTangkeko** [comment]
Hi.  Here's the additional test I did.

I set the BOTO_RETRY to 5,10,3000,0.25, which means the "Default maximum wait time" is 50 mins, right?  

Test 1: Let the Lambda function do the instance stop.  It took 5+mins for it stop.  When I start it again, the "forceful" shutdown message is there.

Test 2: Manually shut down the OS via the RDP, and it took less than 15 secs to completely stop, When I started it again, no "forceful" shutdown messaage is seen.

Test 3 : Used AWS EC2 Console to stop the server.  It took longer the 15 secs but less than 20 secs to stop. When I started it again, no "forceful" shutdown messaage is seen.


My question if my setting is correct.  Why did the lambda function stopped it forcefully around 5mins+, when it should wait for 50 mins?

TIA.

**Comment by gockle** [comment]
Hi @NestorTangkeko The BOTO_RETRY feature looks for specific errors for which it will wait and retry either START/STOP. It could be the error message (its possible there is no error message at all) which is being received when the solution is trying to stop your instance is not configured for BOTO_RETRY. If you are able to execute the EC2 CLI command to shut down your instance and perform a similar check as you have done for Test2 and Test3 and let us know if there is any issue? Also, were you able to try configuring the hibernate option for your instance? Let me know if hibernate is not something which will work for you.

**Comment by NestorTangkeko** [comment]
Hi @gockle ,  is the Instance scheduler using CLI?  I don't think I remember configuring any security credentials on the setup.  Do I run the EC2 CLI command on the server having the issue or run it as a remote CLI command from another server?

**Comment by gockle** [comment]
Hi @NestorTangkeko Instance scheduler doesn't use the CLI it uses python boto3, I requested to run the cli command because I want to understand if the instance shutdown is only causing this issue when boto3 is being used and wanted to rule out other possibilities like the cli.

**Comment by NestorTangkeko** [comment]
Hi @gockle ,

I was able to perform the EC2 CLI successfully.  The server shutdown smoothly, about 15-20 seconds.  There was no "forceful" shutdown message seen, after boot up.

**Comment by JCKrause** [comment]
Hi @NestorTangkeko I was able to reproduce the improper shutdown which logs a kernel-power critical event with a vanilla 2019 instance. I was able to reproduce the issue with the EC2 console, python code written by a co-worker, and with the instance scheduler which proved to me that it was not related to the instance scheduler and that it was most likely an OS related issue. After a lot of testing I found that changing the display power setting from the default of "Never" to any amount of time and being logged out of the server for sometime greater than the setting will cause the shutdown kernel power issue. 

The default Windows AMI's from AWS have this setting set to "Never".

Steps to reproduce:
1. Change the "Power Options - Turn off the display" setting from the default "Never" to 2 minutes
2. Log out of the server
3. Wait at least 3 minutes to be sure the setting would be in effect
4. Shutdown the server via the EC2 console
5. Start the server and login (you may or may not see the "Shutdown Event Tracker" prompt depending on your policy settings)
6. Filter the event log for critical and error events, you should see a critical event and an error event related to the last shutdown

![ShutdownCritical](https://user-images.githubusercontent.com/36509250/126670685-f3373da0-82b0-4b8e-aad5-df0bcf5f9fae.PNG)

![ShutdownError](https://user-images.githubusercontent.com/36509250/126670718-4cc8a373-25d5-426c-9192-38d7c3da23f9.PNG)

7. Remove the event log filter and search the event log for "shutdown's" which will show the last shutdown success status was false

![ShutdownFalse](https://user-images.githubusercontent.com/36509250/126671002-4fa137fb-1e7f-42b1-9188-cc375eccfbe6.PNG)

Steps to verify:
1. Change the "Power Options - Turn off the display" setting back to the default "Never"
2. Log out of the server
3. Wait at least 3 minutes to be sure the setting would be in effect
4. Shutdown the server via the EC2 console
5. Start the server and login
6. Filter the event log for critical and error events, you should not see any critical or error events related to the last shutdown
7. Remove the event log filter and search the event log for "shutdown's" which will show the last shutdown success status was true

![ShutdownTrue](https://user-images.githubusercontent.com/36509250/126670823-cb0091c7-2382-4343-ba22-0e1c56ca5061.PNG)

I hope this resolves the issue for you.

**Comment by NestorTangkeko** [comment]
Hi @JCKrause ,

Got your suggestion.  I've set the power option to "never" as recommended.  The EC2 instances are being used by IT Devt so I can't test it manually.  I'll let the AWS scheduler test it for me.  I will provide a resulting feedback asap.

I'm grateful already even without the result, for the assistance extended on my issue.

Thank you & keep safe.

**Comment by NestorTangkeko** [comment]
Hello @JCKrause ,

Good morning.

Looks like that did it.  Changed the power option to recommended value above, and no improper shutdown warning when the EC2 startup/boot up again.

Thank you for the assistance.
