### ISSUE TITLE
Stop RDS instance permanently

### ISSUE THREAD

**Issue by JoostSaanen** [awslabs/aws-instance-scheduler#196]
Is it possible to stop instances permanently? I see that there is an `override_status` field but doesn't seem to do exactly what I want. Any tips/suggestions?

**Comment by lovepurohit** [comment]
Hi @JoostSaanen 
Yes, you can use the instance scheduler to stop the resource permanently. By using the combination of multiple fields. You need to use both enforced and override_status field to achieve this state. Kindly find the below schedule for your requirement.

`{
  "description": "Instances stopped",
  "enforced": "true",
  "name": "stopped",
  "override_status": "stopped",
  "type": "schedule",
  "use_metrics": false
}`

Kindly let me know if you have any issues.

Thank you

**Comment by rakshb** [comment]
Thanks @lovepurohit. Please confirm if these steps helped addressed your question @JoostSaanen

**Comment by maykays** [comment]
Please re-open this issue if the problem persists.
