### ISSUE TITLE
Unable to update stack with ScheduledServices updates from EC2 to Both

### ISSUE THREAD

**Issue by rohits2290** [awslabs/aws-instance-scheduler#197]
I am trying to update the stack, the update is just changing the ScheduledServices parameter from EC2 to Both.

I have tried: 

1. To update the stack by changing parameter ScheduledServices from EC2 to both
Error: Update_Failed - Custom Resource failed to stabilize in expected time
[scheduler.txt](https://github.com/awslabs/aws-instance-scheduler/files/5192583/scheduler.txt)

2. I have also tried to update the stack by changing the name of the custom parameter from SchedulerConfigHelper to SchedulerConfigHelperV3 with the hope that it'll be a replacement from CloudFormation
Error : Failed to create SchedulerConfigHelperV3 - Custom Resource failed to stabilize in expected time

[scheduler-new.txt](https://github.com/awslabs/aws-instance-scheduler/files/5192582/scheduler-new.txt)

Any suggestions? The EC2 scheduler has been running for more than a year, would not want to redeploy the solution again.

**Comment by gockle** [comment]
@rohits2290 Sorry about the issue, can you confirm the version of the instance scheduler you are currently using in the files you attached it is v1.3.0? and can you try first updating the stack using the latest version of the instance scheduler and try changing the ScheduledServices parameter from EC2 to Both once the update is successful, and let us know if that resolves the issue.

[Instance Scheduler Latest Template v1.3.2](https://s3.amazonaws.com/solutions-reference/aws-instance-scheduler/latest/instance-scheduler.template)

**Comment by rohits2290** [comment]
Thanks @gockle Seems to have resolved the issue, the stack updated fine.
