### ISSUE TITLE
RDS Cluster issue

### ISSUE THREAD

**Issue by dg-consulting** [awslabs/aws-instance-scheduler#198]
Hello,
When we place a schedull tag on a cluster slave, it causes the schedull to crash on all AWS accounts.

Are you going to modify the Lambda code (I suppose to add a Try) to avoid crashing the scheduller? (so that the process can pass to the next resource and not crash for all the account)

Thank you for your feedback.

**Comment by maykays** [comment]
under review

**Comment by gockle** [comment]
@dg-consulting We have resolved this issue in our recent v1.4.0 release, please update the solution to this version and let us know if you still face any issues. Instructions for updating are [here](https://docs.aws.amazon.com/solutions/latest/instance-scheduler/deployment.html).
