### ISSUE TITLE
added notification & priority support

### ISSUE THREAD

**Issue by dg-consulting** [awslabs/aws-instance-scheduler#199]
Hello,

We have several projects that require us to set up notifications on schedulling. Are you going to add this feature?

We also have projects which require us to prioritize between an EC2 and an RDS (ex: started the EC2 only if the RDS is operational)

Thank you for your answers

**Comment by maykays** [comment]
Instance Scheduler supports notifications. Please refer to the implementation guide: [https://docs.aws.amazon.com/solutions/latest/instance-scheduler/considerations.html#logging-notifications](url)

Researching your questions about EC2 dependency on RDS. I will get back to you.
