### ISSUE TITLE
Feature request: State transition notifications

### ISSUE THREAD

**Issue by jgardsentry** [awslabs/aws-instance-scheduler#203]
We need to perform certain internal activities when instances go up and down.  For example, disable monitoring alerts when it goes down and re-enable when it comes up.  Update an internal service that tracks the state of environments.  While there would be a few other ways to accomplish this, I think the best would be for this solution to optionally publish an SNS notification when it takes action on a server.  

There is already an SNS Topic, currently used for warnings and alerts.  Not sure if you'd like to use the same topic or a new one.  But I'd love to (by configurable option on/off), see events something like below.  This would make it much easier to integrate this solution with our internal processes.
```
{
  "timestamp": "2020-09-25T01:23:45",
  "schedule": "my-aws-schedule-name",
  "service": "EC2",
  "id": "i-abcd1234",
  "name": "my-server",
  "account": "0123456789012",
  "region": "us-east-1",
  "action": "stopped"
}
```

**Comment by maykays** [comment]
@jgardsentry This can be accomplished with SNS tagging; however, we will add this feature to the backlog.

**Comment by jgardsentry** [comment]
Thanks @maykays .  Can you describe what you mean by SNS tagging?

**Comment by maykays** [comment]
@jgardsentry If you want to schedule an action when an instance is turned on or off, we recommend you use the native EC2 CloudWatch events. Events are routed to an SNS topic that you can use to integrate with your existing systems. If you would like to know when an instance is scheduled on or off by AWS Instance Scheduler then you can use AWS tagging events to monitor tag changes for an instance following a scheduled action. Refer to the implementation guide for instructions: [Tag your instances](https://docs.aws.amazon.com/solutions/latest/instance-scheduler/deployment.html#step4), [Amazon CloudWatch Metrics](https://docs.aws.amazon.com/solutions/latest/instance-scheduler/cloudwatch.html), [Logging & Notifications](https://docs.aws.amazon.com/solutions/latest/instance-scheduler/considerations.html#logging-notifications.)

**Comment by jgardsentry** [comment]
@maykays Thanks for clarifying, I see what you mean there.

Any chance you'd re-open this request, however?  Configuring Cloudwatch Events in each account & region is a bit of a pain (we have 50+ accounts and use multiple regions), though of course IaC and scripts help.  It just seems that it would be a fairly easy feature to add to the solution and not require "customers" to do the heavy lifting.  Would you consider a pull request for this feature?  It seems as though, while this project is here, you're not directly accepting PR's and actually work on your code in an internal repo.

**Comment by maykays** [comment]
@jgardsentry We will gladly review a PR if you want to submit one. You are correct, we do not directly accept PRs due to security concerns. Thank you for your understanding.
