### ISSUE TITLE
How to handle daylight savings?

### ISSUE THREAD

**Issue by C-Kenny** [awslabs/aws-instance-scheduler#204]
Hi we have `aws-instance-scheduler` deployed against a timezone and configured with tags. Is there a way to account for daylight savings? My understanding is that UTC doesn't account for daylight savings. Thanks

**Comment by gockle** [comment]
@C-Kenny Currently there is no support for configuring timezones against daylight savings, we will take it up as a feature in a future release. For now the only way is to use UTC or any timezone and adjust the periods accordingly.

**Comment by jgardsentry** [comment]
I would think that if your schedule configuration uses a timezone, and **_not_** UTC, then the stop and start times of your instances will continue to occur at the same _**local**_ time after a daylight savings change.

**Comment by gockle** [comment]
Hi @C-Kenny as correctly pointed out by @jgardsentry setting the timezone to US/Eastern or any other value, The solution will make the necessary adjustments for Daylight time saving. We tested it during the weekend of Oct30/Nov1 transition and it worked as expected. Let me know if you still see any issues with scheduling.

**Comment by PrashanthBadaragani** [comment]
@gockle & @jgardsentry , can you please confirm, if we need to change or adjust the periods as well according to the new time zone set ? or once we update the stack with our desired time zone the periods also will be adjusted accordingly ?

**Comment by gockle** [comment]
Hi @PrashanthBadaragani, if the schedules were created with UTC and then the default timezone is modified the schedules should also be updated to the selected timezone, the solution will not update the schedules when the timezone is updated.

**Comment by ancheung01** [comment]
Given it has been 2.5 years, just want to check if instance scheduler still handles daylight savings based on timezone?

**Comment by CrypticCabub** [comment]
Hi @ancheung01 

Instance Scheduler will use whichever timezone is configured for the schedule and daylight savings will be respected in accordance with the timezone selected

**Comment by ancheung01** [comment]
@CrypticCabub 

Thank you very much for confirming!
