### ISSUE TITLE
Schedule resources on specific holidays/dates

### ISSUE THREAD

**Issue by e-power** [awslabs/aws-instance-scheduler#206]
It would be very useful if we could have the scheduler run on specific dates we define, to override the normal day to day schedule on, for example, public holidays.

**Comment by robertcurcio** [comment]
This is pretty challenging. US Federal Holidays would be nice, but each organization celebrates them differently, for example, Columbus Day is not a school holiday. Each country has its holiday schedules too. Another challenge would be the holidays which would be observed on a Saturday or Sunday are celebrated on the following Monday but years between would be celebrated on the actual observed day. 

Cost savings for your Enterprise that include the 10 Federal Holidays would only reduce spending by 3.8% annually. I think the best way for you to avoid holiday spending is to write 10 custom schedules. You can have a maximum of 50 tags per EC2, and apply all the tags 3-5 years ahead.

**Comment by e-power** [comment]
Of course every country/company has differing days, i.e. we are not in the US, and have more than 10 holidays per year. I am not saying to enable holidays for all with a flag, I am saying to allow schedules for specific dates, regardless of it is a holiday or not.

Random example: on 1/10/2021 I would like the scheduler to run and override every other schedule as my company has an offsite event that day where no developers are working.

>I think the best way for you to avoid holiday spending is to write 10 custom schedules.

From what you are saying here this can already be done in a schedule? Maybe I am not using the schedule right if a specific date can be set that I do not know of..

**Comment by maykays** [comment]
@e-power see[ Steps 2 & 3: Configure Periods/Configure Schedules](https://docs.aws.amazon.com/solutions/latest/instance-scheduler/deployment.html) in the implementation guide. This section links to [Appendix A](https://docs.aws.amazon.com/solutions/latest/instance-scheduler/appendix-a.html#available-commands), which describes the arguments to create periods and schedules.
