### ISSUE TITLE
Instances are not powersheduled

### ISSUE THREAD

**Issue by urbinek** [awslabs/aws-instance-scheduler#207]
Hi!

I have problem with fresh deployment  of AIS. It seems like some of instances are not starting, however logs are showing otherwise.

Simple configuration, mon-fri 07:30-19:00 utc, sat-sun stopped all day 

In CloudTrail I can see that tagged instances have been started and tagged:
![obraz](https://user-images.githubusercontent.com/6271355/96876079-4919f100-1478-11eb-96d4-0f76bd081cf4.png)

But some instances were not started:
![obraz](https://user-images.githubusercontent.com/6271355/96876540-deb58080-1478-11eb-983e-df08067fdd31.png)

Our of 6 configured instances 3 are not starting. Powering off works just fine.

I have have no idea how to debug this issue. According to lambda and CloudTrail everything works fine. I even checked logs on OS level and VM was not started/stopped in between schedule periods

**Comment by gockle** [comment]
Hi @urbinek can you provide the EC2 Instance configurations? and can you confirm if the 3 instances which are not starting have encrypted EBS volumes?

**Comment by urbinek** [comment]
hi @gockle, thanks for hint. Indeed instances were encrypted and i didn't created proper role. 

 Whoever i still believe this is a bug where instead of providing kms related error scheduler prints that everything works fine

**Comment by gockle** [comment]
@urbinek So the issue has been resolved once the kms permissions where provided? As far as the error handling is concerned yes I agree that it should provide the relevant information, we will track this as a change to be added to a future release of the solution.

**Comment by urbinek** [comment]
@gockle, yes, issue is resolved now, thank you!
