### ISSUE TITLE
(An error occurred (InvalidParameterCombination) when calling the StartDBInstance operation: aurora-mysql DB instances are not eligible for stopping and starting.)

### ISSUE THREAD

**Issue by mohdziyad** [awslabs/aws-instance-scheduler#208]
ScheduleRDSClusters flag is set to yes. But still it fails to start the cluster back up. Scheduler stops the cluster alright though.

**Comment by gockle** [comment]
Hi @mohdziyad Can you provide the following details for the RDS instance configuration,

**Comment by gockle** [comment]
Hi @mohdziyad Can you provide the following details for the RDS Instances,

* Capacity Type (Provisioned/Serverless)
* Replication features
* Version
* Template selected
* DB Instance size
* Aurora Replica or reader is enabled?

**Comment by gockle** [comment]
Hi @mohdziyad We were able to recreate the issue, if the DB cluster you are trying to schedule using the solution finds Schedule tag in the secondary instance within the cluster this error will come, a temporary work around for this is to only have the schedule tag to the main DB cluster and remove all the tags to the instances within the main DB cluster. We will make changes to resolve this issue in a future release, let me know if the work around resolves the issue for you.

**Comment by mohdziyad** [comment]
That was not the case before. For aurora-mysql, we had to put the tag on both cluster and cluster instance, but for aurora-postgresql, the had to be only on the cluster. Now has something broke this as well ?

**Comment by gockle** [comment]
Hi @mohdziyad  Sorry for the issue, will verify the solution behavior for aurora-postgresql instances and get back to you.

**Comment by gockle** [comment]
Hi @mohdziyad I verified the scenario for both Aurora PostgreSQL and Aurora MySQL engines, when the schedule tag is placed on the specific instances within the cluster the solution is displaying the error. Both DB engines are being scheduled (Start and Stop) as expected when the tags are placed on the main instances, let me know if that resolves the issue.

**Comment by 4wuyan** [comment]
Hello, joining the thread late. I've noticed it as well.

When the tag is placed on the cluster, the scheduler will call `{Start,Stop}DBCluster` and it is working.

When a tag is also placed on the DB instance under the cluster, the scheduler will call `{Start,Stop}DBInstance` and the API call will have error.
> "errorCode": "InvalidParameterCombinationException",
> "errorMessage": "aurora-postgresql DB instances are not eligible for stopping and starting."

Sure, asking people not to set tags on DB instances will solve the issue. But it has the potential that anyone who carelessly puts the tag on their Aurora DB instance will break the scheduler for the entire environment: any DB instance remaining in the list won't be started while the scheduler keeps retrying to start the aurora DB instance and errors out.

**Comment by 4wuyan** [comment]
OK, the last part of my previous comment looks like a consequence of #240. So the problem in #208, i.e. a misconfiguration of the Schedule tag to the cluster, will further trigger the problem in #240.

**Comment by gockle** [comment]
Hi @4wuyan The error that is being displayed in #240 is only being logged (v1.4.0) , the lambda will continue to schedule the remaining instances, if the error needs to be resolved, the tag from the instance in the cluster should be removed. Let me know if you have further questions.

**Comment by 4wuyan** [comment]
Thanks for your reply @gockle .

> if the error needs to be resolved, the tag from the instance in the cluster should be removed.

Yes, it does solve the problem. Thanks.

But it looks like the lambda will _not_ continue when the error in this issue #208 happens. (Maybe I should create a separate issue for that?)

So my last question is, when someone carelessly tags their own Aurora Instance in the cluster, it will affect other peoples' good RDS instances.

**Comment by gockle** [comment]
Hi @4wuyan Please update the stack to the latest version v1.4.0, we have just release this version the fix to this issue is part of the release. You can find the latest templates [here](https://docs.aws.amazon.com/solutions/latest/instance-scheduler/templates.html),

**Comment by CrypticCabub** [comment]
Hi @alejoSubElec.

You would tag the cluster and not the instance. 

The error described occurs when tagging instances that are also part of a cluster as they cannot be started/stopped independently of their parent clusters. Instance Scheduler has a filter that should protect it from attempting to perform these invalid start/stop actions, but the filter was failing to correctly catch certain DB engine types. This has been fixed in our upcoming patch release (v1.5.1).
