### ISSUE TITLE
Conversion of templates to YAML

### ISSUE THREAD

**Issue by sopel** [awslabs/aws-instance-scheduler#21]
Just wanted to ask whether you are open/willing to convert the templates to YAML?

We have started to use them and are exploring improvements for our own use cases that could also submitted upstream eventually, but we really do not enjoy working with JSON anymore, now that the more concise YAML format including support for comments is available, esp. for moderately complex stuff like the [instance-scheduler.template](https://github.com/awslabs/aws-instance-scheduler/blob/4b374a25bad5bd83a59ec8f967805b8aa9ec4f51/source/cloudformation/instance-scheduler.template).

Accordingly, we usually convert every imported template to YAML right away with your very own [aws-cfn-template-flip](https://github.com/awslabs/aws-cfn-template-flip), but that would make submitting pull requests here harder than necessary, so to gauge our options, I'd appreciate a hint whether you might consider that switch in the near future :)

Many thanks,
Steffen

**Comment by arieleeuw** [comment]
Hi Steffen,
At this moment we don't have plans to convert the template to YAML. Now YAM is available, which wasn't the case when we started building this solution, we will consider using YAML instead of JASON depending on the kind of solution. 
I've looked at the cfn-template-flip, nice work! 
regards,
Arie

**Comment by shsenior** [comment]
Closing due to time elapsed since last correspondence. Please re-open this if you are still having an issue.
