### ISSUE TITLE
'Name' property in Period Custom Resource

### ISSUE THREAD

**Issue by rajender025** [awslabs/aws-instance-scheduler#211]
i'm using below template but i receives error:Failed to create resource. but when i remove "Name": "Sat-Stop-11AM" property from period section then it's working find. 

{
	"AWSTemplateFormatVersion": "2010-09-09",
	"Description": "",
	"Resources": {
		"usofficehours": {
			"Type": "Custom::ServiceInstanceSchedule",
			"Properties": {
				"ServiceToken": "<mynamefunctionarn>",
				"UseMaintenanceWindow": "True",
				"StopNewInstances": "False",
				"Enforced": "false",
				"NoStackPrefix": "True",
				"Name": "us-office-hours",
				"Timezone": "UTC",
				"Periods": [{
					"BeginTime": "21:40",
					"EndTime": "23:50",
					"WeekDays": "Sat",
					"Name": "Sat-Stop-11AM"

				}]
			}
		}
	}
}

**Comment by gockle** [comment]
Hi @rajender025 Name is not a defined attribute for the schedule period in the custom resource which is using the cloudformation template to generate the schedule and periods, only the following attributes can be defined BeginTime, Description, EndTime, InstanceType, MonthDays, Months, WeekDays for periods. Refer the documentation for additional information.
* https://docs.aws.amazon.com/solutions/latest/instance-scheduler/appendix-d.html
