### ISSUE TITLE
huge number of lambda invocations (around 296k per day) causing cost increase

### ISSUE THREAD

**Issue by mohdziyad** [awslabs/aws-instance-scheduler#216]
I run this solution in multiple accounts using cross account roles.  more than 200 accounts. And the CW event rule is configured to trigger the lambda every 5 minutes. So it must come around 800 invocations per day. However the CW metric shows that the invocations are in tens of thousands per day. What is causing this ? Are there any other invocations on the lambda ?

**Comment by gockle** [comment]
Hi @mohdziyad The solution collects the instance details (EC2 and RDS) and calls the lambda recursively to actually perform the API calls to start/stop the instances, so as the number of instances in the same account and the number of instances in cross accounts increase the invocation of the lambda increases proportionally. The exact number of calls as you correctly observed will be a number which is more than 800 (based on your configuration) and the actual number will depend on the number of instance and number of accounts configured. This is done in most part for making sure the lambda runs specific duration and doesn't go beyond the set timeout. Let me know if this answers your question.

**Comment by mohdziyad** [comment]
Thank you , that amswers my question.

**Comment by yanivpaz** [comment]
@gockle  - so if I have 10 accounts with 200 ec2s it will invoke lambda 2000 times every 5 minutes?
