### ISSUE TITLE
Schedule with two periods isnt shutting down instances

### ISSUE THREAD

**Issue by hhh0505** [awslabs/aws-instance-scheduler#22]
I've got two periods one to stop at 02:00 and another to start at 08:00, i the tags on the instances are being fetched, but in the state table every instance has a state of "any".

I'm unable to apply these timings on one schedule due to BeginTime being earlier than EndTime. Not sure if there is a bug here or i'm doing something wrong?

This is my schedule and two periods:
"type (S)","name (S)","description (S)","weekdays (SS)","begintime (S)","endtime (S)","periods (SS)","timezone (S)"
"schedule","office-hours","Office hours ",,,,"{ ""office-hours-start"", ""office-hours-stop"" } ","US/Eastern"
"period","office-hours-start","Office hours start","{ ""mon-fri"" } ","08:00",,,
"period","office-hours-stop","Office hours stop","{ ""mon-fri"" } ",,"02:00",,

**Comment by hhh0505** [comment]
closing this as it seems like a duplicate of Nightly period issue.

**Comment by arieleeuw** [comment]
In order configure this you need the following periods

Tue-Sat, start 0:00, stop 2:00
Mon-Fri, start 08:00, stop 23:59

A schedule containing these periods

Starts at workdays at 8am and stops on the next day at 2am.
A fix for an issue that might stop/start at midnight has been deployed to aws answers from where you can update your stack

Regards,
Arie
