### ISSUE TITLE
Need to prevent instances from stopping at the end of a running period

### ISSUE THREAD

**Issue by wbfrench** [awslabs/aws-instance-scheduler#220]
We have some instances running SQL, we want them to start every morning at 5:45am M-F and stop every night at 7:00pm M-F and remain down all weekend. However, the DBAs do not want the Instance Scheduler to stop them.  They want to shut them down every night at 7pm via a SQL job but want the Instance Scheduler to start them.  The 'SQLWakeUp' schedule has the following period associated:
   "Periods": [
      {
         "Weekdays": [
            "mon-fri"
         ],
         "Name": "SQLWakeUp",
         "Type": "period",
         "Begintime": "05:45",
         "Description": "Startup SQL servers at 5:45am M-F"

This has been working fine until recently.  On a couple instances, the DBAs decided to temporarily disable their SQL job from shutting them down. This was fine during the week, their job wouldn't stop the instance and in the morning, since the instance was already up, the Scheduler had nothing to do at 5:45am.  However, and I didn't realize it, although I didn't specify an end time for the period, the period does indeed end at 11:59pm on Friday night, thereby stopping the instances.  Not good, they want the instances to remain up all weekend. I had thought that if I didn't set an end time, then the Scheduler would never stop the instances.  So, I'd like to find a way to have the Scheduler start the instances every morning at 5:45am M-F only, but never stop the instances.  I thought this would be an ideal case for the 'retain_running' option (is it  - or _) but I added it to the schedule and the instances still stopped at midnight.  Thanks in advance for any feedback on the matter.

**Comment by arieleeuw** [comment]
Hi,
I think you can achieve this by adding an addition period to the SQL wakeup for Saturday and Sunday with no start-stop times set. This will keep the instances running on these days.
Hope this works for you
Regards,
A

**Comment by wbfrench** [comment]
Hmm, so just add a period like this to the schedule:

 "Name": "SQLWakeUp2",
         "Type": "period",
         "Description": "SQLWakeUp2",
         "Weekdays": [
            "sat-sun"

I'll give it a shot, thank you!

**Comment by arieleeuw** [comment]
For the days use "sat,sun" to explicitly specify the days,  as the "-" is used to specify a range. From the top of my head I don't remember the enumeration values of the used weekdays.

**Comment by wbfrench** [comment]
Your suggestion worked very well, thank you.
