### ISSUE TITLE
Create Period to start and stop EC2 instance at Nth occurrence of a weekday in the month

### ISSUE THREAD

**Issue by Dovlica10** [awslabs/aws-instance-scheduler#221]
Hello All,
I am trying to create period which will start EC2 instance every 3rd Sunday of the month at 1AM and shut down the instance at 4AM.
When I create period with "weekdays: sun#3" and then check schedule with that specific period from AWS CLI with "scheduler-cli describe-schedule-usage" I receive:   
 "Usage": {
      "2020-12-30": {
         "BillingHours": 0,
         "RunningPeriods": {},
         "BillingSeconds": 0
And so on for all the days of the month.
On the other side when I change to "weekdays: sun", I receive following for each Sunday of the month:
      "2020-12-13": {
         "BillingHours": 3,
         "RunningPeriods": {
            "Sunday-patch-test": {
               "Begin": "12/13/20 01:00:00",
               "End": "12/13/20 04:00:00",
               "BillingHours": 3,
               "BillingSeconds": 10800
Any advice how to configure period to run every Nth occurrence of a weekday in the month?

**Comment by praveenis** [comment]
Hi @Dovlica10 ,

Can you share the created schedule and periods with "weekdays: sun#3" . Can you please share the timezone if used in the schedule or given in the cloudformation parameter.

Also there is an open issue with 'describe-schedule-usage' cli command which shows incorrect results if timezone is other than UTC.  However the functionality works as expected

Thanks,
Praveen

**Comment by Dovlica10** [comment]
Hi @praveenis, thanks for responding.
I don't think it's related to the open issue with 'describe-schedule-usage' cli command, since I get correct results when I remove #3. Also I have been testing this over night few days, so I know that instances are not following this schedule.

scheduler-cli create-period --name sunday-night-patch --begintime 01:00 --endtime 04:00 --weekdays sun#3 --region eu-west-1 --stack Instance-Scheduler 
{
   "Period": {
      "Begintime": "01:00",
      "Endtime": "04:00",
      "Type": "period",
      "Weekdays": [
         "sun#3"
      ],
      "Name": "sunday-night-patch"
   }
}
scheduler-cli create-schedule --name sunday-night-schedule --periods sunday-night-patch --region eu-west-1 --stack Instance-Scheduler --timezone UTC
{
   "Schedule": {
      "RetainRunning": false,
      "Enforced": false,
      "Name": "sunday-night-schedule",
      "StopNewInstances": true,
      "UseMaintenanceWindow": false,
      "Periods": [
         "sunday-night-patch"
      ],
      "UseMetrics": false,
      "Timezone": "UTC",
      "Type": "schedule"
   }
}
End result:
scheduler-cli describe-schedule-usage --name sunday-night-schedule --stack Instance-Scheduler --region eu-west-1 --startdate 20201201 --enddate 20201230
{
   "Usage": {
      "2020-12-30": {
         "BillingHours": 0,
         "RunningPeriods": {},
         "BillingSeconds": 0
      },
      "2020-12-09": {
         "BillingHours": 0,
         "RunningPeriods": {},
         "BillingSeconds": 0
      },
      "2020-12-08": {
         "BillingHours": 0,
         "RunningPeriods": {},
         "BillingSeconds": 0
      },
      "2020-12-07": {
         "BillingHours": 0,
         "RunningPeriods": {},
         "BillingSeconds": 0
      },
      "2020-12-06": {
         "BillingHours": 0,
         "RunningPeriods": {},
         "BillingSeconds": 0
      },
      "2020-12-05": {
         "BillingHours": 0,
         "RunningPeriods": {},
         "BillingSeconds": 0
      },
      "2020-12-04": {
         "BillingHours": 0,
         "RunningPeriods": {},
         "BillingSeconds": 0
      },
      "2020-12-03": {
         "BillingHours": 0,
         "RunningPeriods": {},
         "BillingSeconds": 0
      },
      "2020-12-02": {
         "BillingHours": 0,
         "RunningPeriods": {},
         "BillingSeconds": 0
      },
      "2020-12-01": {
         "BillingHours": 0,
         "RunningPeriods": {},
         "BillingSeconds": 0
      },
      "2020-12-25": {
         "BillingHours": 0,
         "RunningPeriods": {},
         "BillingSeconds": 0
      },
      "2020-12-24": {
         "BillingHours": 0,
         "RunningPeriods": {},
         "BillingSeconds": 0
      },
      "2020-12-27": {
         "BillingHours": 0,
         "RunningPeriods": {},
         "BillingSeconds": 0
      },
      "2020-12-26": {
         "BillingHours": 0,
         "RunningPeriods": {},
         "BillingSeconds": 0
      },
      "2020-12-21": {
         "BillingHours": 0,
         "RunningPeriods": {},
         "BillingSeconds": 0
      },
      "2020-12-20": {
         "BillingHours": 0,
         "RunningPeriods": {},
         "BillingSeconds": 0
      },
      "2020-12-23": {
         "BillingHours": 0,
         "RunningPeriods": {},
         "BillingSeconds": 0
      },
      "2020-12-22": {
         "BillingHours": 0,
         "RunningPeriods": {},
         "BillingSeconds": 0
      },
      "2020-12-29": {
         "BillingHours": 0,
         "RunningPeriods": {},
         "BillingSeconds": 0
      },
      "2020-12-28": {
         "BillingHours": 0,
         "RunningPeriods": {},
         "BillingSeconds": 0
      },
      "2020-12-18": {
         "BillingHours": 0,
         "RunningPeriods": {},
         "BillingSeconds": 0
      },
      "2020-12-19": {
         "BillingHours": 0,
         "RunningPeriods": {},
         "BillingSeconds": 0
      },
      "2020-12-10": {
         "BillingHours": 0,
         "RunningPeriods": {},
         "BillingSeconds": 0
      },
      "2020-12-11": {
         "BillingHours": 0,
         "RunningPeriods": {},
         "BillingSeconds": 0
      },
      "2020-12-12": {
         "BillingHours": 0,
         "RunningPeriods": {},
         "BillingSeconds": 0
      },
      "2020-12-13": {
         "BillingHours": 0,
         "RunningPeriods": {},
         "BillingSeconds": 0
      },
      "2020-12-14": {
         "BillingHours": 0,
         "RunningPeriods": {},
         "BillingSeconds": 0
      },
      "2020-12-15": {
         "BillingHours": 0,
         "RunningPeriods": {},
         "BillingSeconds": 0
      },
      "2020-12-16": {
         "BillingHours": 0,
         "RunningPeriods": {},
         "BillingSeconds": 0
      },
      "2020-12-17": {
         "BillingHours": 0,
         "RunningPeriods": {},
         "BillingSeconds": 0
      }
   },
   "Schedule": "sunday-night-schedule"
}

**Comment by praveenis** [comment]
Hi @Dovlica10 ,

I created the following period with "weekdays: sun#3"and schedule with timezone 'UTC' and got the correct results from describe-schedule-usage. please find the output below. Also can you please confirm what version of Instance Scheduler are you using? the latest version is Instance Scheduler v1.3.3

bash-3.2# scheduler-cli describe-periods --name test-period --stack IS133
{
   "Periods": [
      {
         "Begintime": "01:00",
         "Endtime": "04:59",
         "Weekdays": [
            "sun#3"
         ],
         "Name": "test-period",
         "Type": "period"
      }
   ]
}
bash-3.2# scheduler-cli describe-schedules --name test-schedule --stack IS133
{
   "Schedules": [
      {
         "Timezone": "UTC",
         "Periods": [
            "test-period"
         ],
         "Name": "test-schedule",
         "Type": "schedule"
      }
   ]
}
bash-3.2# scheduler-cli describe-schedule-usage --name test-schedule --stack IS133 --startdate 20201201 --enddate 20201231
{
   "Schedule": "test-schedule",
   "Usage": {
      "2020-12-01": {
         "RunningPeriods": {},
         "BillingSeconds": 0,
         "BillingHours": 0
      },
      "2020-12-02": {
         "RunningPeriods": {},
         "BillingSeconds": 0,
         "BillingHours": 0
      },
      "2020-12-03": {
         "RunningPeriods": {},
         "BillingSeconds": 0,
         "BillingHours": 0
      },
      "2020-12-04": {
         "RunningPeriods": {},
         "BillingSeconds": 0,
         "BillingHours": 0
      },
      "2020-12-05": {
         "RunningPeriods": {},
         "BillingSeconds": 0,
         "BillingHours": 0
      },
      "2020-12-06": {
         "RunningPeriods": {},
         "BillingSeconds": 0,
         "BillingHours": 0
      },
      "2020-12-07": {
         "RunningPeriods": {},
         "BillingSeconds": 0,
         "BillingHours": 0
      },
      "2020-12-08": {
         "RunningPeriods": {},
         "BillingSeconds": 0,
         "BillingHours": 0
      },
      "2020-12-09": {
         "RunningPeriods": {},
         "BillingSeconds": 0,
         "BillingHours": 0
      },
      "2020-12-10": {
         "RunningPeriods": {},
         "BillingSeconds": 0,
         "BillingHours": 0
      },
      "2020-12-11": {
         "RunningPeriods": {},
         "BillingSeconds": 0,
         "BillingHours": 0
      },
      "2020-12-12": {
         "RunningPeriods": {},
         "BillingSeconds": 0,
         "BillingHours": 0
      },
      "2020-12-13": {
         "RunningPeriods": {},
         "BillingSeconds": 0,
         "BillingHours": 0
      },
      "2020-12-14": {
         "RunningPeriods": {},
         "BillingSeconds": 0,
         "BillingHours": 0
      },
      "2020-12-15": {
         "RunningPeriods": {},
         "BillingSeconds": 0,
         "BillingHours": 0
      },
      "2020-12-16": {
         "RunningPeriods": {},
         "BillingSeconds": 0,
         "BillingHours": 0
      },
      "2020-12-17": {
         "RunningPeriods": {},
         "BillingSeconds": 0,
         "BillingHours": 0
      },
      "2020-12-18": {
         "RunningPeriods": {},
         "BillingSeconds": 0,
         "BillingHours": 0
      },
      "2020-12-19": {
         "RunningPeriods": {},
         "BillingSeconds": 0,
         "BillingHours": 0
      },
      "2020-12-20": {
         "RunningPeriods": {
            "Test-period": {
               "Begin": "12/20/20 01:00:00",
               "End": "12/20/20 04:59:00",
               "BillingHours": 4,
               "BillingSeconds": 14340
            }
         },
         "BillingSeconds": 14340,
         "BillingHours": 4
      },
      "2020-12-21": {
         "RunningPeriods": {},
         "BillingSeconds": 0,
         "BillingHours": 0
      },
      "2020-12-22": {
         "RunningPeriods": {},
         "BillingSeconds": 0,
         "BillingHours": 0
      },
      "2020-12-23": {
         "RunningPeriods": {},
         "BillingSeconds": 0,
         "BillingHours": 0
      },
      "2020-12-24": {
         "RunningPeriods": {},
         "BillingSeconds": 0,
         "BillingHours": 0
      },
      "2020-12-25": {
         "RunningPeriods": {},
         "BillingSeconds": 0,
         "BillingHours": 0
      },
      "2020-12-26": {
         "RunningPeriods": {},
         "BillingSeconds": 0,
         "BillingHours": 0
      },
      "2020-12-27": {
         "RunningPeriods": {},
         "BillingSeconds": 0,
         "BillingHours": 0
      },
      "2020-12-28": {
         "RunningPeriods": {},
         "BillingSeconds": 0,
         "BillingHours": 0
      },
      "2020-12-29": {
         "RunningPeriods": {},
         "BillingSeconds": 0,
         "BillingHours": 0
      },
      "2020-12-30": {
         "RunningPeriods": {},
         "BillingSeconds": 0,
         "BillingHours": 0
      },
      "2020-12-31": {
         "RunningPeriods": {},
         "BillingSeconds": 0,
         "BillingHours": 0
      }
   }
}

Thanks,
Praveen

**Comment by Dovlica10** [comment]
Hi @praveenis,

Thanks again for follow up.
I guess that you kinda solved the issue for me. We are using first version of instance-scheduler 1.1 or ( 2.2.2.0 in CF stack). I found this closed ticket: https://github.com/awslabs/aws-instance-scheduler/issues/114 , which pretty much explains the issue that I am having, so I guess I will need to update the stack with the latest version of instance-scheduler.

Thanks again for your help, and I think this ticket can be closed, although I didn't have time to perform the upgrade, I am sure it will solve the issue.

**Comment by KALX9** [comment]
I have a similar situation. But here i don't want to mention the start or end time. I just want to mention the amount of time. Suppose if instance starts at 07:00 Hrs, it should be stopped after 2 Hours at 09:00 Hrs...  or if it has started at 11:00 Hrs after 2 hours, it should stop at 13:00 Hrs.
