### ISSUE TITLE
Upgrade path?

### ISSUE THREAD

**Issue by robertaspinall** [awslabs/aws-instance-scheduler#224]
Sorry if this isn't the right place to post this.  What is the upgrade path for updating the instance scheduler to the latest version?

**Comment by gockle** [comment]
@robertaspinall If I understand this, you want the updated templates to the latest version? You can find them [here](https://docs.aws.amazon.com/solutions/latest/instance-scheduler/templates.html)

**Comment by robertaspinall** [comment]
I'm asking what the expected actions to upgrade are.  Do we have to remove
the current stack?

Robert Aspinall

NOAA's National Ocean Service
CO-OPS/Information Systems Division
1305 East-West Highway
Bldg. SSMC4, Station Id 6314
Silver Spring, MD 20910

Robert.Aspinall@noaa.gov

**Comment by gockle** [comment]
Hi @robertaspinall you can just update the current stack, using the options Update > Replace current template > Provide the template [link](https://s3.amazonaws.com/solutions-reference/aws-instance-scheduler/latest/instance-scheduler.template).
