### ISSUE TITLE
Starting an EC2 instance manually while being under schedule cause issues 

### ISSUE THREAD

**Issue by Medalibi** [awslabs/aws-instance-scheduler#229]
Hi,

The solution seemed to be working fine with no issues at first. But then I needed to start one fo the machine manually to do some minor changes and awaiting it to be shut down when the next 30mins window of verification arrives, but nothing happens. If I make a change manually I need to fix it manually. This is what I get in the logs:

```
2021-02-10 - 10:00:31.982 - DEBUG   : No running periods at this time found in schedule "MastTest1" for this time, desired state is stopped
2021-02-10 - 10:00:31.982 - DEBUG: Desired state for instance from schedule "MastTest1" is stopped, last desired state was stopped, actual state is running
...
2021-02-10 - 10:00:31.983 - INFO    : Scheduler result {'XXXXXXXXXX': {'started': {}, 'stopped': {}, 'resized': {}}}
```

Is there a way to force the scheduler to ignore the status of the VM and whatever its tag "status" was saying at the time and follow the DynamoDB periods?

Cheers,
Mo

**Comment by gockle** [comment]
@Medalibi Can you provide the schedule and period configuration for the instance, it will help us reproduce the issue. Thanks.

**Comment by Medalibi** [comment]
It is an Ubuntu 18.04 server the base ami from aws running g4dn.2xlarge. The schedule was uk-office-time and it was supposed to be closed ove the weekend but it was still running

**Comment by gockle** [comment]
@Medalibi thanks for the information, can you provide what is the value set for the attributes Hibernate, Enforced, RetainRunning set to in the schedule "uk-office-time"?, Also if you can provide the entire Period JSON attribute that would help.

**Comment by Medalibi** [comment]
they are all empty. oh, I assume I need to add true in Enforced right? apologies I use the dynamo DB interface to make changes and never scrolled to see what is back there.

**Comment by gockle** [comment]
Hi @Medalibi There are a few options to ensure the instances either run or continue to behave according to the schedule when manually started/stopped, I suggest going through the [Implementation Guide](https://docs.aws.amazon.com/solutions/latest/instance-scheduler/instance-scheduler.pdf) Refer to the section "Schedules" and go through the options available, If you continue to face any issues please let us know.
