### ISSUE TITLE
I specify a start time only, but the running period is ~23:59.

### ISSUE THREAD

**Issue by espozbob** [awslabs/aws-instance-scheduler#23]
I specify a start time only, but the running period is ~23:59.
(I am not fixed the issue yet -https://github.com/awslabs/aws-instance-scheduler/pull/19)

---
Implementation Guide said:

--endtime
The time when the running period stops. If begintime and endtime are not specified,
the running period is 00:00 – 23:59. 
...

If you specify a start time only, **the instance must be stopped manually**. Similarly,
if you specify a stop time only, the instance must be started manually. If you don’t specify
either time, the solution uses the days of the week, days of the month, or months rules to start
and stop instances. 

https://s3.amazonaws.com/solutions-reference/aws-instance-scheduler/latest/instance-scheduler.pdf
---
and would it be helpful to add a "override_status=running" field in this situation?

**Comment by arieleeuw** [comment]
Bob,
Are you using any day or weekday settings in the period?

**Comment by espozbob** [comment]
Yes, period settings :
weekday:[1], begintime:”15:30” 

Umm..If the weekly schedule is set, Is it only running until the day of the week?

**Comment by arieleeuw** [comment]
Exactly. 
All criteria that are defined for a period are used (AND) to determine the desired state. So if you use one, or more, of the date/day criteria thse must all match for that period. If a schedule has multple periods then the instance will run if at least one (OR) has a desired running state. The last desired state is stored, and the scheduler will take action if the new desired state differs from the last desired state. This allows you to manually start/stop, without the scheduler stop/start it again if the instance state differs from the desired state. It will as not use the actual instance state. If you use the enforced flag on a schedule then it will compare the actual instance state with the desired state, so the scheduler will always try to bring the instance back again into the desired schedule state.
If you use a start time only, the state before the start time will be any (basically leave status as is) and running if time >= start time. It will stop at 23:59 if you use a day/date setting for that period and no other period in that schudule has a desired running state.

Hope this expains the logic and ideas behind the scheduler logic
Regards
Arie

**Comment by espozbob** [comment]
Then...
periods1  = weekdays:{"0"}, endtime:”23:59”
periods2  = weekdays:{"1"}, begintime:”15:30”  
periods3  = weekdays:{"2-6"}, endtime:”23:59”

schedule = [periods1, periods2, periods3]

This will  try to start at 15:30 PM on Tuesday and will be stopped manually on the other day.
is it correct?

**Comment by shsenior** [comment]
Closing due to time elapsed since last correspondence. Please re-open this if you are still having an issue.
