### ISSUE TITLE
feature request: support for multiple schedules in different timezones for a resource

### ISSUE THREAD

**Issue by baronnenate** [awslabs/aws-instance-scheduler#233]
I have one EC2 instance that I want to keep running in both India & UK office hours but it doesn't seem possible unless you create a schedule in GMT or UTC to cover both UK & India office hours. 
In essence - would it be possible to have an instance running that is up for both UK & India timezones during a certain period (ie. office hours, say  @8am-6pm)?

**Comment by praveenis** [comment]
Hi @baronnenate ,

Thanks for the feature request. we will move this to our backlog and review it. 

With the current design it is not possible however you can find the period and timezone which covers both UK and India office hours and create a schedule based on that.

8 am IST is 3:30 am BST and 6 pm IST is 1:30 pm BST. so you can create a schedule in UK timezone with period begin time @ 3:30 and end time @ 18:00. 

Please let me know if you need any help.

Thanks,
Praveen

**Comment by baronnenate** [comment]
thanks! yeah that's what I've done as a workaround.
cheers!
