### ISSUE TITLE
Possibility of schedule MON-SUN 06:00-01:00

### ISSUE THREAD

**Issue by rohits2290** [awslabs/aws-instance-scheduler#234]
We're using Scheduler (version v1.3.3)

Wondering if it is possible to set up a schedule that starts at 6am in the morning (say Monday) and switches off 1am (Tuesday) > Starts 06am (Tuesday) and switches off 1am (Wednesday) and so forth...

I tried to deploy the stack to see if it does work.
Errored out - Error message.
Failed to create resource. The following resource(s) failed to create: [MonSun0600To0100].

**Comment by arieleeuw** [comment]
Hi, the way to do this is create a schedule that contains multiple periods so the running periods overlapping the day boundary consists of 2 adjacent periods.

```
-Mon start at 6:00, stop 23:59
-Tue start 0:00, stop 01:00

-Tue start 06:00, stop 23:59
-Wed start 0:00, stop 1:00
```

etc...

The scheduler logic will detect the adjacent periods (start of next period == end last period + 1 min) and will keep the instance running at the end of the first period of the adjacent set

**Comment by praveenis** [comment]
Hi @rohits2290 ,

Currently we are not supporting end time earlier than begin time. Please see the multiple workarounds below.

**Workaround 1:**
As @arieleeuw suggested, you can create multiple periods for the schedule. 

Create Periods:
-name start-mon-6am -weekdays mon -begintime 06:00
-name stop-tue-1am -weekdays tue -endtime 01:00
-name start-tue-6am -weekdays tue -begintime 06:00
-name stop-wed-1am -weekdays wed -endtime 01:00
-name start-wed-6am -weekdays wed -begintime 06:00
.
.
.

Create Schedule:
-name schedule-start6am-end1am -periods start-mon-6am,stop-tue-1am,start-tue-6am,stop-wed-1am,start-wed-6am,..

**Workaround 2:**
Find a timezone where your end time 01:00 hrs is earlier than 23:59 hrs in different timezone and use it in the schedule.

let's say 06:00 - 01:00 hrs IST is 00:30 - 07:30 hrs  in UTC .

you can create a period and schedule using UTC timezone like below.

Create Periods:
-name start-stop-UTC-period -weekdays mon-sun -begintime 00:30 -endtime 07:30

Create Schedule:
-name start-stop-UTC-schedule -periods start-stop-UTC-period -timezone UTC

Please let us know if you need any help.

Thanks,
Praveen

**Comment by rohits2290** [comment]
Thanks all

Ended up with a config like this. Since we wanted it to be repeated daily.

Periods:
        - Description: MON-SUN 06:00-00:00
          BeginTime: '06:00'
          EndTime: '23:59'
          WeekDays: Mon-Sun
        - Description: MON-SUN 00:00-01:00
          BeginTime: '00:00'
          EndTime: '01:00'
          WeekDays: Mon-Sun
