### ISSUE TITLE
Issue with SSM Maintenance window DB table not being populated.

### ISSUE THREAD

**Issue by keagansc2** [awslabs/aws-instance-scheduler#237]
Hi there,

Whilst creating a standard Scheduler and adding a single "nested" stack to have an additional schedule utilize an SSM maintenance window I notice that in the main DB table (StackName)-ConfigTable the specific Custom schedule is added correctly however, in the underlying Maintenance window DB table that specific Window is not added (table like {StackName}-MaintenanceWindowTable)

I searched through the code running specific events however, could not ever find a call to the "{PathToScheduler}\instance-scheduler\schedulers\ec2_service.py" which does the updating and editing of this table.

I will attach my zipped file which contains the code and the "InstanceScheduler.yaml"/NestedSchedule.yaml" template files I ran for my template. Running these did not add the "Custom" schedule's Maintenance window to the underlying DB, as this DB is utilized to "start" the instance in an allotted time before the window.

Please do let me know if you need anything else.
[instance-scheduler.zip](https://github.com/awslabs/aws-instance-scheduler/files/6164877/instance-scheduler.zip)

**Comment by gockle** [comment]
Hi @keagansc2 Instance scheduler has an issue where the solution is unable to load SSM Maintenance windows (even those not used in the solution) are defined in any timezone other than UTC, the work around for this is to define all the maintenance windows in UTC. We are currently working on fixing this issue in the next release.
