### ISSUE TITLE
General guidance on instance scheduler Runtime environment

### ISSUE THREAD

**Issue by JagadeswarYaramala-moodys** [awslabs/aws-instance-scheduler#241]
Hi Team,

we are using Instance scheduler in our accounts which are version 1.2.0. in that instance schedulers, the Lambda fucntions are running on Python 2.7, as the python 2.7 is getting EOL, so we decided to change the runtime environment to python 3.7. please let us know is there any impact in doing this change.

**Comment by gockle** [comment]
Hi @JagadeswarYaramala-moodys 

The version 1.2.0 is currently not being supported, even if the changes are made to the runtime environment, the solution might behave unpredictably, You can update the solution to the latest version, by updating the stack you are currently running.

[Instance Scheduler Latest Template](https://s3.amazonaws.com/solutions-reference/aws-instance-scheduler/latest/instance-scheduler.template),

Let me know if you face any issues upgrading to the newer version.
