### ISSUE TITLE
Instance scheduler multiple tag support, and holiday

### ISSUE THREAD

**Issue by chatchai-komrangded** [awslabs/aws-instance-scheduler#243]
I'm curious if we can configure to support multiple tag, with support variety holiday for each individual country. ex: TH, and US will have difference holiday day.

EX: 
  To stop all 50 instances that have been tag in "holiday-th" (Which may include weekday)

**Comment by chatchai-komrangded** [comment]
Duplicate with https://github.com/awslabs/aws-instance-scheduler/issues/231

**Comment by rakshb** [comment]
@chatchai-komrangded Thanks this is already in our backlog and will be reviewed for a future release!
