### ISSUE TITLE
Period "p" is not defined

### ISSUE THREAD

**Issue by sandwormusmc** [awslabs/aws-instance-scheduler#247]
I've deployed the solution, set up periods and associated them with schedules, and am receiving the below error in the logs:

ERROR   : Period "d" used in schedule "{'use_maintenance_window': 'true', 'timezone': 'US/Central', 'description': 'development systems schedule', 'periods': 'dev', 'name': 'dev', 'type': 'schedule'}" is not defined

I've tried multiple methods of defining "periods" in the DynamoDB config table, also attempting {"dev"} because I noticed the region was defined as {"us-west-2"} after deploying the CloudFormation stack.

Relevant DynamoDB items:

The below returns 'Period "d"' error.  For a very similar schedule definition that uses a single period named "prod", the error is instead 'Period "p" used in schedule...'
`{
  "type": {
    "S": "schedule"
  },
  "name": {
    "S": "dev"
  },
  "use_maintenance_window": {
    "S": "true"
  },
  "timezone": {
    "S": "US/Central"
  },
  "description": {
    "S": "development systems schedule"
  },
  "periods": {
    "S": "dev"
  }
}`

Period definition for "dev":
`{
  "type": {
    "S": "period"
  },
  "name": {
    "S": "dev"
  },
  "begintime": {
    "S": "00:00"
  },
  "description": {
    "S": "development systems schedule"
  },
  "endtime": {
    "S": "12:00"
  },
  "weekdays": {
    "S": "mon-fri"
  }
}`

**Comment by sandwormusmc** [comment]
I worked around this goofy bug by changing the period names to "d" and "p", respectively, and the previous errors went away.

But, an interesting thing is that I updated the "dev" schedule to point to point to period "d" (which works), but I hadn't changed the "prod" schedule to point to "p" yet and it was still "prod".  The error now became:

ERROR : Period "r" used in schedule "{'use_maintenance_window': 'true', 'timezone': 'US/Central', 'description': 'production systems schedule', 'periods': 'prod', 'name': 'prod', 'type': 'schedule'}" is not defined

Is the value of "periods" being exploded by character and then attempting to look for a period for each letter of the word?  Seems like very strange behavior... since it was erroring on the first letter, and now that I have a "p" period (but not one named "r"), I think the error was masked but is now obvious.

I tried to code dive to find the place where the config table is referenced, but it's pretty deep in multiple function calls... I'm sure once I update my "prod" schedule to point to just "p" for the period (I've already updated the associated period item in DDB), it will work.

Still, odd regression/bug/something.

**Comment by sandwormusmc** [comment]
Update, after modifying my "prod" schedule to point to "p" period, it works.  As a result of this bug, the current code base seems to impose a one character limit on period names.  I wonder what affect this will have on other users of instance scheduler that upgrade to the new version, and have periods defined with more than one character...

**Comment by gockle** [comment]
Hi @sandwormusmc The periods attribute in the scheduler json should be in the format, StringSet

```
 {
  "type": {
    "S": "schedule"
  },
  "name": {
    "S": "DevSchedule"
  },
  "use_maintenance_window": {
    "BOOL": false
  },
  "stop_new_instances": {
    "BOOL": true
  },
  "use_metrics": {
    "BOOL": false
  },
  "hibernate": {
    "BOOL": false
  },
  "enforced": {
    "BOOL": true
  },
  "retain_running": {
    "BOOL": false
  },
  "description": {
    "S": "Development environment schedule"
  },
  "periods": {
    "SS": [
      "devPeriod1",
      "devPeriod2"
    ]
  }
}
```

Let me know if using StringSet resolves the issue for you.

**Comment by sandwormusmc** [comment]
Yeah it most likely will.  My implementation was since removed, as the customer did not choose to move forward with instance scheduling (unrelated to this issue).

Appreciate you sharing the schema for direct management via DynamoDB.  My challenges with the CLI lead me to edit the DynamoDB table directly, and I wasn't able to find a schema in the documentation, so that part was trial and error as well.

Perhaps an update of the schema definitions in the documentation would be helpful?

**Comment by maykays** [comment]
Thank you for the feedback. Closing this issue for now.
