### ISSUE TITLE
Feature request - add timestamp to tag value of the action parameter

### ISSUE THREAD

**Issue by sandwormusmc** [awslabs/aws-instance-scheduler#248]
I've finally gotten the solution to work, with some feedback and a bug as separate issues from this issue.  It would be a nice to have if the solution allowed for adding a timestamp to the end of the tag it updates for stop and start actions.

My deployment parameters for the CloudFormation stack specified:

`StartedTags | instance-scheduler-action=started`
`StoppedTags | instance-scheduler-action=stopped`

So, the script updates the value of the instance-scheduler-action tag to the last action it took on the scheduled resource.  It was a sort of ah-ha moment that I had to think through, perhaps the documentation could be updated to make that more obvious.

Regarding the feature request, it would be nice if I could also append a timestamp to "started" and "stopped" above, so it would be something like "stopped-at-2021042804:00" or something.

**Comment by gockle** [comment]
Hi @sandwormusmc Instance scheduler has the option to add tags with timestamp for the instances, please refer to the document [here](https://docs.aws.amazon.com/solutions/latest/instance-scheduler/components.html), refer to the section "Automated tagging".

**Comment by sandwormusmc** [comment]
Perfect, thanks!
