### ISSUE TITLE
Editing the DynamoDB in Cloudformation Launch.

### ISSUE THREAD

**Issue by pompbediener** [awslabs/aws-instance-scheduler#26]
Hi, 

I see that the DynamoDB is filled by this part of the code

```json
"Settings": {
            "Metrics": {
                "Url": "https://metrics.awssolutionsbuilder.com/generic",
                "SolutionId": "S00030"
            },
```

But i exactly would like to edit this part, is there any option to do so? 
So it will choice a different URL but with the same info.

Regards,

**Comment by arieleeuw** [comment]
Hi,

We use this for customers that opt-in for sending us anonymous usage data to get a better insight in how are solutions are uses. If you want to collect this information yourself you can certainly use your own url and capture this data in your own service that handles the calls.

regards,
Arie

**Comment by shsenior** [comment]
Closing due to time elapsed since last correspondence. Please re-open this if you are still having an issue.
