### ISSUE TITLE
EC2 instances booting problem in the same remote region

### ISSUE THREAD

**Issue by Sebizbir** [awslabs/aws-instance-scheduler#262]
Main stack is reading remote account (the other stack implemented there).
Some of the instances within the same remote region are starting at the beginning of the schedule some do not (only starting for few seconds then stopped).
EC2 nodes are tagged to point to the same schedule. They differ only about size.

Pleas see logs collected.
2021-07-15T06:00:25.429+02:00	INFO : Starting instances EC2:i-0c93e... (schdule-test-1), EC2:i-0bdd9... (test2) in region eu-central-1
2021-07-15T06:02:26.104+02:00	INFO : Fetching ec2 instances for account ... in region eu-central-1
	2021-07-15T06:02:26.522+02:00	DEBUG : Selected ec2 instance i-0c93e... in state (running)
	2021-07-15T06:02:26.522+02:00	DEBUG : Selected ec2 instance i-0bdd9... in state (stopped)

###
2021-07-15T06:00:28.674+02:00
INFO    : Sending anonymous metrics data: 
{
    "TimeStamp": "2021-07-15T04:00:28.674074",
    "UUID": "dc252051-...",
    "Data": [
        {
            "Service": "ec2",
            "Action": "Started",
            "InstanceType": "t2.micro",
            "Instances": 1
        },
        {
            "Service": "ec2",
            "Action": "Started",
            "InstanceType": "m5.xlarge",
            "Instances": 1
        }
    ],
    "Solution": "S00030",
    "Version": "v1.4.0"
}
###

even metadata state shows started - m5.xlarge instance is stopped within the scheduled time.
The machine which behaves correctly has had tagged for many days ago.
The machine which not started fully (starting then stopped) was tagged outside schedule time day before starting time came on.

**Comment by gockle** [comment]
Hi @Sebizbir Are you able to manually start the instances in the ec2 console?

 If Yes 
* can you check AWS CloudTrail in the account where the solution is installed
 and
* the AWS CloudTrail in the account and also in the account where the ec2 instance is, 

for API calls to the particular instance, 

you can look up the API logs using the Event History > Select Resource Name > Provide the instance id or the name and search for the API StartInstance? 

To give more context Instance scheduler, retrieves the list of the instances with the Schedule key and then check the desired state, if the instance should be in started/running state, the solution will only make a single start instance API call and poll the instance status, it will not make any further calls to stop the instance.

**Comment by Sebizbir** [comment]
Hi @gockle ,
I discover some instances have Volumes encrypted.
I added the necessary kms permission to Scheduler role.
The question is, do I have to update every role with "schedule" in the name even on remote accounts?
Or only the main one "<stackname>- SchedulerRole-<id>"
Cheers

**Comment by gockle** [comment]
@Sebizbir Each role created in the remote accounts which will be used by Instance scheduler should be updated.
