### ISSUE TITLE
no output when stackset deployed

### ISSUE THREAD

**Issue by ssheff** [awslabs/aws-instance-scheduler#270]
Hi,
We have deployed instance scheduler to more than 100 accounts however the output that is specified in the CFT is not getting back to us ARNs of the roles that being created in those accounts so we need go in each account and capture that information. Is there a way that it could be enhanced/automated that all the ARN will be returned back to the CFT in the stacksets?

**Comment by gockle** [comment]
Hi @ssheff Unfortunately this is currently a major limitation of the solution, that the IAM roles have to be added manually to the main solution stack, we are working on improving this scenario in the next release for the solution, Currently in the v1.4.0 version the IAM roles have to be manually updated in the main stack.

**Comment by ssheff** [comment]
thank you so very much for the answer and clarification
I have created lambda function that scans for the ARN created and populate parameter store
