### ISSUE TITLE
CrossAccountRoles exceeding 4096 characters

### ISSUE THREAD

**Issue by FrankFioretti** [awslabs/aws-instance-scheduler#272]
We have run into the issue of having too many cross account roles such that we are exceeding the maximum number of characters that Cloudformation supports in a given parameter. We have explored the option of adding an additional parameter and using a Join function however this requires us to change the parameter type from CommaDelimitedList to String (because you can only use Join on Strings), which then is processed incorrectly by the Lambda function and is thus written incorrectly to the DynamoDB table.

**Comment by gockle** [comment]
Hi @FrankFioretti You can save the cross account roles in a AWS Systems Manager Parameter Store and then use the name of the Parameter store reference in the format `{param:[SSM_PARAM_NAME]}`, You can find further instructions [here](https://docs.aws.amazon.com/solutions/latest/instance-scheduler/deployment.html), refer the section __Cross-account roles__

**Comment by FrankFioretti** [comment]
Thank you. From the documentation I didnt assume that the SSM parameter was natively supported, rather that it was another option that existed that would need to be built out on our end. I will mark this as solved. Thank you again.
