### ISSUE TITLE
Custom Resource

### ISSUE THREAD

**Issue by mccoyaoife** [awslabs/aws-instance-scheduler#29]
Hello,
If I try to deploy the custom resource that aws provides in the aws instance scheduler into the same account the main instance schedule stack is deployed, it deploys successfully and i can create new schedules/periods. 

However, if I try to deploy the custom resource into an account that doesnt have the main instance scheduler stack deployed, it fails and complains about permissions on the lambda. For example:

User: arn:aws:sts::876481310196:assumed-role/*/* is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:us-east-1:601468343342:function:n0252813-instance-scheduler-dev-InstanceSchedulerMain

Is there a way of being to allow any user in any other account to invoke this lambda so that I can create custom resources in other accounts.

**Comment by arieleeuw** [comment]
Sure, you have to add the principal of that  to the resource permissions for the lambda function.

- https://docs.aws.amazon.com/cli/latest/reference/lambda/add-permission.html
- https://docs.aws.amazon.com/lambda/latest/dg/access-control-resource-based.html

If you wan to do this by customising the template search for SchedulerInvokePermission in the CFN template and add the principal there
