### ISSUE TITLE
use_metrics

### ISSUE THREAD

**Issue by maximrozin** [awslabs/aws-instance-scheduler#31]
While troubleshooting why the custom metrics have not been created, I found out that when use_metrics is _not_ set on the schedule level (left undefined), the value set on the global config level will be ignored and no custom metrics will be created (even if it set to _true_ on the global config level). Wanted to check if this was the intention.

I don't believe that it's supposed to be like that since it means that:
1. In order to enable custom metrics, it **must** be configured on the schedule level (irrespective of the setting on the global config level).
2. The setting of use_metrics on the global config level doesn't have any effect.

PS I really like AWS Instance Scheduler!

**Comment by arieleeuw** [comment]
Hi thanks for your feedback.
You are right, the global setting is not used as the schedule value if no metrics setting is used at a schedule level. For now you have to set the metrics at schedule level.
We've found the issue and it wil be included in the next maintenance release

p.s. we're glad you like the scheduler :-)

**Comment by maximrozin** [comment]
Thank you @arieleeuw

**Comment by YaminiMuralidharen** [comment]
Hi ,
Can you provide reference code or documentation for creating custom metrics with schedule and service dimensions within the custom schedule resource


Thanks

**Comment by maximrozin** [comment]
Are you referencing the custom CloudFormation resource? I edited the DynamoDB table manually.

**Comment by YaminiMuralidharen** [comment]
Yes, I tried to set the use_metrics within the custom resource created using the cloud formation template, but it dint work out.So, I edited the dynamodb table manually and it worked.

Thank you

**Comment by arieleeuw** [comment]
Hope this helps:

```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "Test Schedule ",
  "Resources": {
    "TestSchedule": {
      "Type": "Custom::ServiceInstanceSchedule",
      "Properties": {
        "ServiceToken": "arn:aws:lambda:<stack region here:>:<your account number here> :function:InstanceScheduler-InstanceSchedulerMain",
        "Description": "Working hours",
        "Enforced": "True",
        "Timezone": "Europe/Amsterdam",
        "Metrics" : "True",
        "Periods": [
          {
            "Description": "Opening hours on weekdays",
            "BeginTime": "09:00",
            "EndTime": "23:59",
            "WeekDays": "Mon-Fri"
          },
          {
            "Description": "Opening hours in weekend",
            "BeginTime": "09:00",
            "EndTime": "23:59",
            "WeekDays": "Sat-Sun"
          }
        ]
      }
    }
  }
}

```

**Comment by YaminiMuralidharen** [comment]
Thank you @arieleeuw for the template .The use_metrics 's value got updated in dynamodb table after i included **Metrics: 'True'** in my yaml template.  Previously ,I used **Use_metrics:'True'** in my template and it failed to update the stack.

**Comment by shsenior** [comment]
Closing due to time elapsed since last correspondence. Please re-open this if you are still having an issue.
