### ISSUE TITLE
Dynamodb Global config not able to update. Unable to update around 150 cross account roles in config table

### ISSUE THREAD

**Issue by KeerthigaKrishnan** [awslabs/aws-instance-scheduler#33]
We have 150 cross account roles, when I try to update on dynamodb table cross account role, it is not able to take more than 80 accounts due to the item limit, I guess. Is there any way, that we can create seperate list and call as value in cross account roles. or any other way of doing it..

**Comment by vijaysat1** [comment]
thank you and we will consider this for the next release

**Comment by arieleeuw** [comment]
As typing in 150 arn's in a textbox is not an optimal solution anyway...
In OpsAutomator we have an option to provide lists of arn in text files to be placed in the config bucket. As we don't have such a bucket we did not use this here. In Ops Automator V2 we have an option to use {ssm:<name>} placeholders in parameters for values stores in the SSM parameter store. Especially for cases like yours this might be a much better solution. Will this work for you?

**Comment by KeerthigaKrishnan** [comment]
It was an issue with dynamodb transient response issue in table.. once it is fixed.. I am able to append the values thru cloudformation template. Besides, I will try your solution as well and let u know. how it works

**Comment by arieleeuw** [comment]
To make maintaining long lists of cross account arn's easier next maintenance update (1.2) will integrate with SSM Parameter store

**Comment by shsenior** [comment]
Fixed in v1.2.0
