### ISSUE TITLE
Typo in custom schedule parameter "UseMaintenaceWindow"

### ISSUE THREAD

**Issue by simon-levitt-sirca** [awslabs/aws-instance-scheduler#34]
There is a typo in the "UseMaintenanceWindow" parameter: [UseMaintenaceWindow](https://github.com/awslabs/aws-instance-scheduler/blob/ac4f73569cefebb08ef06af45d6742024be544de/source/code/requesthandlers/schedule_resource_handler.py#L49)

**Comment by arieleeuw** [comment]
Thanks for reporting this, we'll fix this in the next Maintenance release

**Comment by shsenior** [comment]
Fixed in v1.2.0
