### ISSUE TITLE
No profile support

### ISSUE THREAD

**Issue by jwsomis** [awslabs/aws-instance-scheduler#35]
The scheduler-cli does not support non-default profiles with the --profile option.

Input: scheduler-cli create-period --profile example --name weekdays --stack InstanceScheduler --weekdays mon-fri --begintime 6:00 --endtime 18:00 

Output: 
usage: scheduler-cli [-h] [--version]
                     
                     {describe-periods,create-period,update-schedule,update-period,describe-schedule-usage,describe-schedules,delete-schedule,create-schedule,delete-period}
                     ...
scheduler-cli: error: unrecognized arguments: --profile example

**Comment by arieleeuw** [comment]
This is correct, in this release the default profile is uses. We will look into this and see if we can add profile support in a next update

**Comment by danielshiplett** [comment]
Has there been any more progress on this?  This would be a very valuable feature.

**Comment by arieleeuw** [comment]
It's in the upcoming maintenance release, it will be out soon


On 26 Feb 2019, at 19:11, Daniel Shiplett <notifications@github.com<mailto:notifications@github.com>> wrote:


Has there been any more progress on this? This would be a very valuable feature.

**Comment by trojanski** [comment]
Any update on release date @arieleeuw ?

**Comment by shsenior** [comment]
Fixed in v1.2.0
