### ISSUE TITLE
issue with override_status

### ISSUE THREAD

**Issue by hhh0505** [awslabs/aws-instance-scheduler#36]
I'm attempting to Stop the instances but would like the ability to manually start the instances and not start them automatically. I've used the override_status to help with this and set it as Stopped. Currently i see mt state table showing all stopped , but   that isn't the actual status of my instances. How can i achieve this?

Periods:
period1= Tue-Sat, start 0:00, stop 2:00
period2= Mon-Fri, start 08:00, stop 23:59

Schedule:
{
  "description": {
    "S": "Office hours"
  },
  "name": {
    "S": "office-hours"
  },
  "override_status": {
    "S": "stopped"
  },
  "periods": {
    "SS": [
      "period1",
      "period2"
    ]
  },
  "timezone": {
    "S": "US/Eastern"
  },
  "type": {
    "S": "schedule"
  }
}

**Comment by arieleeuw** [comment]
Hi,
By using the overtide_status you're telling the scheduler to heep them stopped at all times (overriding every period)
If you eant a scenario to start the instance manual and have them stopped automatically then create a schedule with just one period, just defining the stop time. 
period -> stop -> time you want to stop the instances
schedule -> period defined above
We do not recommend combining a start or stop only period combined with other periods in a schedule on the same day

**Comment by shsenior** [comment]
Closing due to time elapsed since last correspondence. Please re-open this if you are still having an issue.
