### ISSUE TITLE
Instance scheduler does not work as a nested CloudFormation template

### ISSUE THREAD

**Issue by maxbog** [awslabs/aws-instance-scheduler#37]
Hi,

I launched instance scheduler as a nested template and the CloudWatch events handler does not run.
Failing event:
```
2018-07-19 - 06:30:33.847 - DEBUG : Request was not handled, no handler was able to handle this type of request
{
    "account": "xxxxxxxxxxxx",
    "region": "eu-west-1",
    "detail": {},
    "detail-type": "Scheduled Event",
    "source": "aws.events",
    "version": "0",
    "time": "2018-07-19T06:30:00Z",
    "id": "1af4d438-dfaf-400b-4acb-423c339cb0cf",
    "resources": [
        "arn:aws:events:eu-west-1:xxxxxxxxxxxx:rule/Instance-Scheduler-Scheduler-19BIN6Q-SchedulerRule-14DFUXIRT279M"
    ]
}
```

After debugging, it seems that the handler expects the event arn to begin with `arn:aws:events:eu-west-1:xxxxxxxxxxxx:rule/Instance-Scheduler-Scheduler-19BIN6QDFUVTN-SchedulerRule`.

It seems that the rule name was truncated and the handler does not run

**Comment by arieleeuw** [comment]
Hi,

The limit for the stackname for a deployed scheduler is 36 characters. We asked the technical writers to document this limit in the Implementers Guide.

regards,
Arie

**Comment by caglabaylan** [comment]
Hi,
I am facing with exactly same error, however my stack name does not exceed 36 characters and resource arn is true. What would be the reason?
Thanks

**Comment by arieleeuw** [comment]
The documentation has been updated with the max length of the stack name

**Comment by shsenior** [comment]
Resolving this issue as the documentation was updated to reflect this.
