### ISSUE TITLE
Problem starting all instances in a schedule/period

### ISSUE THREAD

**Issue by dghadge** [awslabs/aws-instance-scheduler#38]
Hello -- Thanks for this great tool. I have around 5 instances that use a single schedule but multiple periods. The periods differ only by the stop time not start time. All those periods are tied to that single schedule.  It stops all the instances in the schedule however while starting it starts only 3 out of 5. These instances are not in ASG or anything special. 
Spent a lot of time debugging - any help is appreciated.

**Comment by arieleeuw** [comment]
Hi,
Can you check if these instances have encrypted volumes?
In that case allow the kms:CreateGrant action to the Scheduler and cross account roles.
Hopes this helps
Arie


Sent from my iPhone

On 6 Aug 2018, at 15:02, Dnyanesh Ghadge <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello -- Thanks for this great tool. I have around 5 instances that use a single schedule but multiple periods. All those periods are tied to that single schedule. It stops all the instances in the schedule however while starting it starts only 3 out of 5. These instances are not in ASG or anything special.
Spent a lot of time debugging - any help is appreciated.

**Comment by dghadge** [comment]
Ughh; i should have know this. Yes they have encrypted volumes. Thank You for quick response and awesome support !!

**Comment by arieleeuw** [comment]
No problem, took me a couple of hours as well ;-)
I've asked our tech writer to update the documentation


Sent from my iPhone

On 6 Aug 2018, at 15:36, Dnyanesh Ghadge <notifications@github.com<mailto:notifications@github.com>> wrote:


Ughh; i should have know this. Yes they have encrypted volumes. Thank You for quick response and awesome support !!

**Comment by shsenior** [comment]
Resolving this issue as the documentation was updated to reflect this.
