### ISSUE TITLE
Trying to schedule an Instance to Stop at 1AM and Start at 6AM. 

### ISSUE THREAD

**Issue by krishnaCNagalla** [awslabs/aws-instance-scheduler#39]
Hi, 

I am trying to implement Instance Scheduler to stop an Instance at 1 am and Start is back at 6 am. As far as I know the end time must be always greater than the start time in a period. So it didn't work when I directly specified those times in a period. 
Then to accomplish this, I have created 2 periods, 1 period with endtime as 1 am and other period with begintime as 6 am. this didn't work either. 
Can you help me with this task ?

**Comment by arieleeuw** [comment]
Hi,

yes, you need two periods in the schedule to do this type of scheduling

First create a period that is active from midnight until 1am

$ scheduler-cli create-period --stack InstanceScheduler --name period-midnight-1am --begintime 00:00 --endtime 01:00
{
   "Period": {
      "Endtime": "01:00", 
      "Type": "period", 
      "Name": "period-midnight-1am", 
      "Begintime": "00:00"
   }
}

Then a second one that is active from 6am until midnight (note we use 23:59 as begin must be < than end). The scheduler (make sure you have the latest version installed) will detect that the two periods are adjacent and will not stop the instance at 23:59 as there is the next period that starts one minute later at 00:00)

$ scheduler-cli create-period --stack InstanceScheduler --name period-6am-midnight --begintime 06:00 --endtime 23:59
{
   "Period": {
      "Endtime": "23:59", 
      "Type": "period", 
      "Name": "period-6am-midnight", 
      "Begintime": "06:00"
   }
}


Now create the schedule that contains there periods and also specifies the timezone


$scheduler-cli create-schedule --stack InstanceScheduler --name schedule-stop-between-1am-6am --periods period-midnight-1am,period-6am-midnight --timezone Europe/London

{
   "Schedule": {
      "RetainRunning": false, 
      "Enforced": false, 
      "Name": "schedule-stop-between-1am-6am", 
      "StopNewInstances": true, 
      "Periods": [
         "period-6am-midnight", 
         "period-midnight-1am"
      ], 
      "Timezone": "Europe/London", 
      "Type": "schedule"
   }
}


Now tag (Using the tag-name "Schedule" assuming you used the default name") the Instance with the name of the schedule "schedule-stop-between-1am-6am"

A great way to check if the schedule is scheduling as you expect is to use the following command that shows which periods are active in a specific date range (default if you don't specify a start/end date is today). As you see the scheduler logic detects the adjacent periods in the schedule.

$ scheduler-cli describe-schedule-usage --stack InstanceScheduler --name schedule-stop-between-1am-6am
{
   "Usage": {
      "2018-08-17": {
         "BillingHours": 19, 
         "RunningPeriods": {
            "Period-6am-midnight": {
               "Begin": "08/17/18 06:00:00", 
               "End": "08/18/18 00:00:00", 
               "BillingHours": 18, 
               "BillingSeconds": 64800
            }, 
            "Period-midnight-1am": {
               "Begin": "08/17/18 00:00:00", 
               "End": "08/17/18 01:00:00", 
               "BillingHours": 1, 
               "BillingSeconds": 3600
            }
         }, 
         "BillingSeconds": 68400
      }
   }, 
   "Schedule": "schedule-stop-between-1am-6am"
}

Hope this answers your question
Arie

**Comment by krishnaCNagalla** [comment]
Hi arieleeuw, 

Thank you so much for your response and I apologize for the late response. I some how was able to figure out the same solution base on your other answers in this space and didn't get a chance to get back here to thank you. 

This solution worked for me perfectly. Thank you so much again for you time and response.

**Comment by shsenior** [comment]
Closing due to time elapsed since last correspondence. Please re-open this if you are still having an issue.
