### ISSUE TITLE
AWS Instance Scheduler not working in local mode

### ISSUE THREAD

**Issue by lovepurohit** [awslabs/aws-instance-scheduler#40]
Hi,

I am trying to execute the instance scheduler locally by `python run_scheduler_local.py Test-Instance-Scheduler`. 
It executes for a bit but it gives a error after a couple of seconds.
Error: `ModuleNotFoundError: No module named 'instance_states'` 
But as I can see module is available in the code.

Any suggestion for remediation of error and how to run it locally?

**Comment by arieleeuw** [comment]
Hi,

Hope I can help you with this checklist

-Make sure to run the code from the directory where the run_scheduler_local.py is located. If you run from an environment like PyCharm make sure the folder named "code" as "Sources root", and set the Current working directory to the directory that contains the "run_scheduler_local.py" file
-Make sure you have the boto3 library installed in the python environment you are using
-The code is build and will only work with Python 2.7

Hope this helps

**Comment by lovepurohit** [comment]
Hi, 

I already have boto3 library installed. Also I am running the file from the directory where the run_scheduler_local.py is located. I think issue might be the python version. I have python 3.6 installed on my machine. 

Is there any way to run it on latest version of python or do I have to downgrade the python to python 2.7?

**Comment by arieleeuw** [comment]
Hi,

You can run python2 and 3 side by side on your system and use an alias for python that points to the default version, or explicitly use python2 when running the python script.Make sure to have the libraries you need installed for you Python version as both version have their own library directories.

For python development I strongly recommend to create a virtual environment (
https://virtualenv.pypa.io/en/stable) for your project in which you install all the required libraries.

If you wan to work on a specific project activate the environment you created for it or configure it in the IDE you're working is e.g. PyCharm (
https://www.jetbrains.com/help/pycharm/configuring-python-interpreter.htm)
l

**Comment by eikenb** [comment]
I was just working through this and using python2.7 and a virtualenv with boto3, etc. installed you can get it to work. The main thing that is missing is that you need to have the environment variables set (I just duplicated all of them to be sure) and you need permissions of course. I created a test user/policy using the same access the scheduler gets.

I'd suggest maybe a brief README in the source/code/ folder documenting how to get  run_scheduler_local.py to run.

**Comment by shsenior** [comment]
Closing due to time elapsed since last correspondence. Please re-open this if you are still having an issue.
