### ISSUE TITLE
Can I disable the RDS snapshot creation before stopping it

### ISSUE THREAD

**Issue by prateek121** [awslabs/aws-instance-scheduler#43]
Hello 
As I understand RDS snapshot is taken before stopping it ?
May I know can we disable this feature and how 
Is there a flag out of box ?

**Comment by arieleeuw** [comment]
Hi,

The current version always makes the snapshot for a stoped RDS instance.We might add this as an option int he schedule in a next release. For now you can open the Scheduler Lambda function the the Lambda console. In the source tree on the left side of the code window, navigate to the schedulers module and open the rds_service.py file. On line 337 you can remove the DBSnapshotIdentifier in the call to stop_db_instance_with_retries.

`     client.stop_db_instance_with_retries(DBInstanceIdentifier=inst.id, DBSnapshotIdentifier=snapshot_name)`

**Comment by prateek121** [comment]
Thanks this helps.
