### ISSUE TITLE
same schedule name value for RDS and EC2 but different time for start/stop

### ISSUE THREAD

**Issue by prateek121** [awslabs/aws-instance-scheduler#44]
How can I have different schedule period for RDS and EC2 
for same tagged value ?
say "office-hours" 9-5 for ec2 
but for rds 8.30 to 5.30.

This is to have a mechanism for RDS to start before apps in ec2 come up ??

**Comment by maximrozin** [comment]
You can define 2 separate schedules - one for EC2 and another for RDS, each with its own name/tag value.

**Comment by arieleeuw** [comment]
Confirmed, you need two separate schedules.

**Comment by arieleeuw** [comment]
Personally I would go for the two separate schedules as this makes the delay more visible than having it "hidden" in the code.

For the upcoming release of Ops Automator V2 we're testing a feature that let's you Automatically create tags on EC2/RDS instances if an EC2/RDS instance is stopped. So for example you can have a task that stops the EC2 instance, a task that is triggered by the event of the stopped EC2 instance that creates a tag on selected RDS instance, and a last task that is triggered by the setting that tag on the RDS instance to stop is. This way we can chain the starting and stopping of EC2 and RDS instances.
regards,
Arie

**Comment by shsenior** [comment]
Fixed in v1.2.0
