### ISSUE TITLE
Support for Aurora

### ISSUE THREAD

**Issue by maximrozin** [awslabs/aws-instance-scheduler#45]
Hello,

With the recent [announcement](https://aws.amazon.com/about-aws/whats-new/2018/09/amazon-aurora-stop-and-start/) of stop/start functionality for Aurora clusters, wanted to ask if there a plan for Instance Scheduler to support Aurora databases.

Kind Regards,
Maxim

**Comment by arieleeuw** [comment]
The plan is to have this in the next maintenance release after we ran our tests

If you want to enable it in the meantime in you van find the line that checks for "aurora" clusters in module "schedulers -> rds_service.py line 207-209

            if rds_inst["Engine"] in ["aurora"]:
                self._logger.debug(DEBUG_UNSUPPORTED_ENGINE, rds_inst["Engine"], db_id)
                return False

**Comment by arieleeuw** [comment]
Aurora will be enabled in next maintenance release together with Multi-AZ instances

**Comment by arieleeuw** [comment]
Hi Maxim,

We publish the modified code shortly after a new release on AWSLabs. What you can do is subscribe to notifications for this project repository.

Hope this will work for you

Arie

On 7 Nov 2018, at 11:26, Maxim Rozin <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the update Arie!
Is there any way to be notified when it gets updated or perhaps to see a change log of every release?

**Comment by electric** [comment]
Hi @arieleeuw - any chance I can get added to the preview for Aurora compatibility? Please email eru.goodwin@serato.com

Thank you

**Comment by vehvis** [comment]
Any ETA on the "next maintenance release"? Been a while.

**Comment by FrankFioretti** [comment]
Any Update?

**Comment by shsenior** [comment]
Fixed in v1.2.0
