### ISSUE TITLE
Trying to schedule an instance from 12PM to 12AM i.e., 12PM to 00:00AM

### ISSUE THREAD

**Issue by lovepurohit** [awslabs/aws-instance-scheduler#48]
Hi,

I am trying to schedule an instance from 12PM to 12AM that is the other half of the day but as i simply put the begin time as 12:00 and endtime as 00:00 it is not working. 
Can you please help me out on this?

Thank you

**Comment by maximrozin** [comment]
Change the endtime from 00:00 to 23:59, and it should work.
You can find more information [here](https://github.com/awslabs/aws-instance-scheduler/issues/12).

**Comment by lovepurohit** [comment]
I have a confusion. That the instance scheduler checks on every five minutes. and if the endtime 23:59. Won't it skip the stop time and will not stop the instance?

**Comment by arieleeuw** [comment]
The scheduler will run at 00:00 and see that the time is not in the period 12:00-23:59 and will stop the instance. Each time the scheduler will run it will calculated the desired state based on the periods in the schedule and the current (localised) time.

**Comment by lovepurohit** [comment]
Ok, I will update the period end time and verifies whether it will stop the instance or not.
Highly grateful for such fast response and for your help.

**Comment by shsenior** [comment]
Closing due to time elapsed since last correspondence. Please re-open this if you are still having an issue.
