### ISSUE TITLE
Tags and Instances

### ISSUE THREAD

**Issue by joeskop** [awslabs/aws-instance-scheduler#5]
Hi to everyone.

I tried to integrate the instance scheduler, according the AWS Implementation guide. I have these errors:

1) Start and stop tags don't works;
2) Some instances, for some reason I can't find, are correctly stopped but they don't come up and I have this message all day: (`Desired state for instance from schedule "daily-stop" is running, last desired state was running, actual state is stopped`)
3) I can't find Cloud Metrics on CloudWatch.

BTW, thank you for your work!

**Comment by arieleeuw** [comment]
1) Tags are only set when the instance is started/stopped by the scheduler. Looking into possible delay between the instance going into a starting state after the call to start the instance has been made
2) If instances are manually stopped in a running period the manual stopped state is honoured by the scheduler. As shown in the log the last desired state was running, which matches the schedule state, so the instance is not started. The instance will be started at the beginning of the next running period. If you want to enforce the schedule state then use the "enforced" flag with a value True for the used schedule.
3) The default CloudWatch Metrics settings must be enabled from the metrics parameter in the main template. The default metrics for an schedule can be specified by setting the metrics parameter to True for the specific schedule. See https://docs.aws.amazon.com/solutions/latest/instance-scheduler/components.html   "schedule definitions"

**Comment by arieleeuw** [comment]
We looked into the issue mentioned in 1) (see above)

We're testing an update that should address the issue if there is a delay between the start/stop of the instance and the instance getting into the desired state.
Please also note that if the instance is already in the desired state (manually started/stopped) at the start/end of a period the scheduler will detect this and will not take any action and by design, will not tag the instances

**Comment by joeskop** [comment]
Hi,
tried again and again to solve the 3rd question about CloudWatch.
Tried to correct, change conf, rebuild... Nothing at all. I'm unable to see custom metrics on my Cloudwatch metrics.
Any suggestion?

**Comment by georgebearden** [comment]
We've released several updates to this solution since this issue was created. Please let us know if you are still experiencing this problem.
