### ISSUE TITLE
How to schedule to shutdown all ec2 and then RDS

### ISSUE THREAD

**Issue by prateek121** [awslabs/aws-instance-scheduler#50]
How can I customise the lambda to run the shutdown of all ec2's  first and 
then followed by RDS  ?

**Comment by arieleeuw** [comment]
With Instance Scheduler the simplest solution is to have two "overlapping" schedules. for example:
RDS Schedule 8:55-17:05
EC2 Schedule 9:00-17:00

As the scheduler is generic and does schedule service instances of "any" kind there is no easy way to do this in the existing code. If you really want to do it in an event based way, you could have a separate lambda that is triggered by the new aws.tag events (https://aws.amazon.com/about-aws/whats-new/2018/09/changes-to-tags-on-aws-resources-now-generate-amazon-cloudwatch-events/). Let the start/stop of the instances put specific tags on the started/stopped instances. The lambda can then react by starting/stopping the eC2/RDS instances or out a scheduler tag on it to do so.

In Ops Automator V2 that will be available later this year there is an option to "chain" starts/stops of EC2 and RDS instances. (stopped EC2 instances can trigger task that sets tag on other ECS instances, this tag will trigger another task to stop these instances) An we can do the same the other way around by letting a started RDS instance trigger a start tag on EC2 instances.

**Comment by prateek121** [comment]
Thanks @arieleeuw
