### ISSUE TITLE
Errors:   Request was not handled, no handler was able to handle this type of request

### ISSUE THREAD

**Issue by prateek121** [awslabs/aws-instance-scheduler#52]
Ive enabled the trace and get the above message for every event and scheduler doesnt work.
{
    "account": "xxxxxx",
    "region": "xxxx",
    "detail": {},
    "detail-type": "Scheduled Event",
    "source": "aws.events",
    "version": "0",
    "time": "2018-10-17T02:15:00Z",
    "id": "xxx",
    "resources": [
        "arn:aws:events:region:1234:rule/EC2-SchedulerRule"
    ]
}

Mind you. .. I have changed the cfn logical id's by appending with ec2 and rds to respective resources logical id as Im tryin to depoy two makeshift with schedulers for ec2 and rds separately.
 so I dont see them working now for some reason.

**Comment by arieleeuw** [comment]
the easiest solution I would recommend is to:

-Use the default installation
-Create two schedules with names as below
   -ec2-schedule -> start 9:00, stop 17:00
   -rds-schedule -> start 8:50, stop 17:10
-Tag the ec2 and rds instances you want to control 
   -EC2 instances Schedule=ec2-schedule
   -RDS instances Schedule=rds-schedule

RDS instance starts at 8:00, followed by ECS instances at 9:00. 
ECS Instances stops at 17:00, followed by RDS instances at 17:10

**Comment by prateek121** [comment]
Nah, I happen to debug more to how/where the scheduler handles  request with name of scheduler logical id in clouwatch even handler. This is what I see where its sort of hardCoded.
`startswith("{}-SchedulerRule`

So now my logicalIds are **SchedulerRuleEC2** instead of **EC2SchedulerRuleEC2**.
This basically works now, So Ive separated to two lambdas one for each service.
