### ISSUE TITLE
Ensure Stop - Question/Feature Request

### ISSUE THREAD

**Issue by kiml42** [awslabs/aws-instance-scheduler#54]
Is there a way to ensure an instance is stopped, regardless of what state it's in and overriding manual state changes?
Our use case for this is stopping a test server in the evening, after everyone will have finished working on it. This server may or may not be needed on any given day, so starting it up must be manual, but we want to ensure it is stopped, after work, without relying on the users to remember.

Sorry if this is the wrong place to ask this sort of question, if so, could you please point me to the correct forum.

Thanks,

Richard

**Comment by arieleeuw** [comment]
Hi Richard,

The way to do is is to add the enforced flag on the schedule and set it to true. If the instance is started outside of the periods in your schedule it is stopped at the next iteration of the scheduler. But also if the instance is stopped within these periods it will be started again. The function of the enforced flag is to keep the instance in the state as you defined in the schedule.

https://docs.aws.amazon.com/solutions/latest/instance-scheduler/components.html

Hopes this helps
Arie

**Comment by kiml42** [comment]
Thanks Arie,
That's useful to know, but if I'm understanding correctly, it doesn't provide a way to have a schedule that turns an instance off without turning it on again at some point.
Thanks again,
Richard

**Comment by arieleeuw** [comment]
Richard,

If you omit the starttime the desired state will be "any" before the stop time and the scheduler will leave the state "as is". A stop time combined with the enforced flag the instance will be stopped (and stopped again if it is started) after the specified stop time.

regards,
Arie

**Comment by kiml42** [comment]
> 
> 
> Hi Richard,
> 
> The way to do is is to add the enforced flag on the schedule and set it to true. If the instance is started outside of the periods in your schedule it is stopped at the next iteration of the scheduler. But also if the instance is stopped within these periods it will be started again. The function of the enforced flag is to keep the instance in the state as you defined in the schedule.
> 
> https://docs.aws.amazon.com/solutions/latest/instance-scheduler/components.html
> 
> Hopes this helps
> Arie

The Period Rules section of the link provided by Arie seems to answer my question.
