### ISSUE TITLE
Time-based schedule delay or suppression

### ISSUE THREAD

**Issue by jgard** [awslabs/aws-instance-scheduler#59]
We're considering adopting this solution to replace a custom, home-grown solution with far fewer features.

One feature we'd be losing, however, is the ability to suppress scheduling activity until a certain date in the future.  For example, when we have a server scheduled down, but want to bring it up for patching or an application deployment, we'd like to leave it on for, say, 2 hours.  We have a configuration field we call "scheduling disabled until" that accepts a datetime.  Once that datetime is passed, scheduling resumes.

I think that this could become a new attribute/field in a Schedule object.  The benefit of this is to adjust the schedule at the beginning of the activity (for example, patching), and not have to come around at the end and modify the schedule again.

**Comment by arieleeuw** [comment]
In our next update we have an option to specify the name of an Systems Manager Maintenance Window. Based on the execution times and duration of this windows, we add an additional period in which the instances in that schedule will be running for patching etc. 
For add hoc patching or other maintenance work you can also use the override option, of a schedule to keep the instances running whilst this option is set to “running”.
Hope this works for you.

**Comment by shsenior** [comment]
Fixed in v1.2.0
