### ISSUE TITLE
Resize happens in the second cycle after the instance gets stopped in the first lambda cycle

### ISSUE THREAD

**Issue by omshankar1** [awslabs/aws-instance-scheduler#6]
The resizing of the ec2 instance happens in 2 stages In the first lambda run the ec2 instance gets stopped on trigger. In the second lambda run the resize happens. For the duration between first and second run the ec2 instance is in stopped state.
Details as follows:
Schedule:
Resize |   |   | { "Aus-nonoff-hours2@t2.nano", "Aus-nonoff-hours@t2.nano", "Aus-office-hours@t2.micro" } | Australia/Sydney
Period:
Aus-nonoff-hours |   | { "mon-fri" } |   |   | 19:00 | 23:59
Aus-nonoff-hours2 |   | { "mon-fri" } |   |   | 00:00 | 09:00
Aus-office-hours |   | { "mon-fri" } |   |   | 08:00 | 19:00

**Comment by arieleeuw** [comment]
This is correct. The scheduler will check the actual type of the instance and if this is not the specified type it will stop the instance. In the next cycle of the scheduler it will first resize the type of the instance and then start it. Unfortunately it is not possible to resize an instance without this stop/start. In these situations the scheduler interval may be set to 1 minute to minimise the period between stop/start

**Comment by shsenior** [comment]
Closing due to time elapsed since last correspondence. Please re-open this if you are still having an issue.
