### ISSUE TITLE
ECS scheduler required

### ISSUE THREAD

**Issue by cbanciu667** [awslabs/aws-instance-scheduler#60]
Hi,

If possible, would be nice to add an ECS scheduler to stop tasks and ECS cluster nodes.
I have already built something similar: https://github.com/cbanciu667/lambda-ecs-scheduler

You can use my code as base, if it helps, and merge it into aws-instance-scheduler (adding second lambda function, second S3 bucket and so on).

Thank you!
Cosmin Banciu

**Comment by JoostSaanen** [comment]
Interesting. I 'stop' my ECS cluster by decrease my desired instances in the underlying ASG to 0 (with a scheduled cloudwatch event).

**Comment by cbanciu667** [comment]
Hi Joost,

First of all each service from the ECS cluster should have the DesiredCount set to 0 so the tasks  are stopped gradually, otherwise when starting them again it takes a lot of time.
After that, what i do, is to set desired count of the ASG also to 0.
When starting i setup a delay of 60 seconds and lambda timeout is set to 150 but is not enough for many ECS clusters.
Meanwhile i managed to merge my solution with the aws-instance-scheduler, but is not production ready yet, is a lot of refactoring. I post my updates via Pull request.

Cosmin

**Comment by rdkls** [comment]
Hi @cbanciu667 how did you go with this? I couldn't find the PR?
It'd be really helpful for teams wanting to Cost Op ...
