### ISSUE TITLE
Security issues that need fixes ...

### ISSUE THREAD

**Issue by smitaskamat** [awslabs/aws-instance-scheduler#61]
Server side Encryption is required for dynamo db tables.

**Comment by smitaskamat** [comment]
Can you plan to release a new version of the CF template with the security fixes ?  We would like to use the awslabs signed off version of the template rather than maintain our own fork with fixes.

**Comment by arieleeuw** [comment]
We do not plan to add the encryption by default as it could cause loss of data in situation where users use it to update existing stacks and the tables get replaced. If you classify the schedule configuration and instance id's in the internal working table as confidential, then we recommend to make the changes to the template as suggested and deploy it as a new stack.
We publish our code and templates on AWS Labs to allow customers to customise the solutions for their specific needs.

**Comment by smitaskamat** [comment]
Ok.  Thanks for suggesting the fix.  We will incorporate this in our forked copy of the CF template.
