### ISSUE TITLE
RDS Aurora start/stop_db_cluster

### ISSUE THREAD

**Issue by FallenHoot** [awslabs/aws-instance-scheduler#64]
Hi,

Currently trying to use AWS Instance Scheduler to 'start/stop_db_cluster'. I noticed in the code within the 'rds_service.py' file the following is written:

`  if rds_inst["Engine"] in ["aurora"]:
            self._logger.debug(DEBUG_UNSUPPORTED_ENGINE, rds_inst["Engine"], db_id)
            return False`

If my understanding is correct. This will flag aurora as the DB Engine and skip it. 

My question is: Will AWS Instance Scheduler support the use of 'start/stop_db_cluster' as it currently only supports 'start/stop_db_instance()'

**Comment by arieleeuw** [comment]
We will support RDS Aurora, Multi-AZ instances  and EC2 Hibernation in our next maintenance release that is under test. I can provide you with link to preview if you're interested in testing it.

**Comment by FallenHoot** [comment]
@arieleeuw 
That would be great if you could do that.

**Comment by dziemid** [comment]
Hey @arieleeuw - we're interested in this as well. Could you give me access to version that supports  RDS Aurora and Multi-AZ instances?  greg.dziemidowicz@chargefox.com

**Comment by FallenHoot** [comment]
@arieleeuw 
I have been testing this out for the past 2 weeks now. It works like a charm. I haven't noticed any issues. 
Thanks again for this.

**Comment by davidchannon** [comment]
Hi @arieleeuw could you give me access to the RDS Aurora and Multi-AZ release please?

**Comment by arieleeuw** [comment]
David,
How can I contact you to send you the links?

**Comment by davidchannon** [comment]
david@skgnet.com would be great :)

thanks


David Channon
AWS Consultant and Data Architect
david@skgnet.com
07795 696 229

**Comment by davidholsgrove** [comment]
Hi @arieleeuw is there a branch where we could have a look at the upcoming release of Instance Scheduler? I'm a long time user / first time needer of Aurora support 😄

**Comment by nassifnassif** [comment]
Hi @arieleeuw, we are interested in testing the RDS Aurora Cluster start/stop cluster, if you can please provide the link for the preview, that would be greatly appreciated.
Thanks,
Nassif

**Comment by nalindak** [comment]
Hi @arieleeuw, we are also very interested in testing the RDS Aurora Cluster start/strop feature, I have emailed `aws-ops-automator@amazon.com` few days ago requesting the beta URL, however we haven't received any response from them. Would you be able to check this and let us know.
Thanks

**Comment by electric** [comment]
Hello - also interested in Aurora Cluster preview - please send links to eru.goodwin@serato.com

**Comment by derekvh1** [comment]
Hi , I'm also interested in the cluster preview. I'd much appreciate receiving the links ! 
derek.vanhove@blubird.eu
Thanks, Derek

**Comment by lpavan225** [comment]
Hi , i am also interested in the cluster preview, Can you please send the links to lekkalapavan.r@brillio.com

**Comment by HanjongKim** [comment]
Hi , I am also interested in the cluster preview, Can you please send the links to hjkim259@lotte.com

**Comment by FrankFioretti** [comment]
I would also like access to the beta. Please send the link to frank.fioretti@att.net

**Comment by FrankFioretti** [comment]
> @arieleeuw
> I have been testing this out for the past 2 weeks now. It works like a charm. I haven't noticed any issues.
> Thanks again for this.

Are you able to provide the link to the updated version privately? It doesn't seem like there's been much activity on this in a while.

**Comment by kobarasukimaro** [comment]
Hello,  I am also interested in the cluster preview, Can you please send the links to 
ryosei2001jp@gmail.com

**Comment by ziyadmhd** [comment]
Hello,
I am also interested in the cluster preview. Please send the links to:
mohammed.ziyad@broadridge.com

**Comment by shsenior** [comment]
Fixed in v1.2.0
