### ISSUE TITLE
Security Issue on lambda of the CF template.

### ISSUE THREAD

**Issue by smitaskamat** [awslabs/aws-instance-scheduler#65]
Lambda function does not have a Security Group -- This is the other security issue that came up when we deployed this CF template.  We would like to use the cross account nature of the Instance Scheduler (i.e. host the Scheduler in a "shared services account" and have it manage the scheduling of resources in other accounts).  However the lambda function needs a SG that keeps it private.  Can you also help with this ?

**Comment by arieleeuw** [comment]
Instance Scheduler is actually designed for this.
The Instance Scheduler stack is deployed in the shared services account.
We provide an additional stack that can be used to create a cross-account role with enough permissions to perform the required API calls in the accounts you want to manage instances.
The ARN's of these roles are then configured in the cross-account role setting of the main Instance Scheduler stack in the shared services account (or in a SSM Parameter store value as we support this in the upcoming 1.2 release). The Lambda function of the Instance Scheduler will then assume these roles to schedule the EC2 and RDS instances in the accounts of these roles. This is described in step 5 of the setup procedure at https://docs.aws.amazon.com/solutions/latest/instance-scheduler/deployment.html

**Comment by shsenior** [comment]
Fixed in v1.2.0
