### ISSUE TITLE
AWS Instance Scheduler deprecated by Systems Manager (SSM)?

### ISSUE THREAD

**Issue by AndrewCi** [awslabs/aws-instance-scheduler#66]
On November 18th, 2018 AWS released the ability to use Systems Manager (SSM) to execute Automations in Multiple AWS Regions and Accounts (cross-account functionality). These automation documents include the ability to start/stop EC2 and RDS instances which can be integrated using maintenance windows with the ability to set timezone etc. providing very similar functionality to the AWS Instance Scheduler.

Given this overlap, does AWS plan to deprecate Instance Scheduler? I'm struggling to find the value of using this tool which incurs additional tech infrastructure over SSM which is already provided by AWS? Am I missing something? Curious on thoughts.

Resource: https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-automation-multiple-accounts-and-regions.html

**Comment by arieleeuw** [comment]
We currently don't have plans to deprecate Instance Scheduler 

Shortly we will release an update supporting:

- Scheduling of RDS Aurora Clusters
- Scheduling of Multi-AZ RDS instances
- EC2 Hibernation
- Integration with SSM parameter store for cross account roles
- Integration with SSM EC2 maintenance windows as running periods
- CLI enhancements and profile support

**Comment by FallenHoot** [comment]
@arieleeuw 
Any news on this new release?

**Comment by shsenior** [comment]
Fixed in v1.2.0
