### ISSUE TITLE
Issues with aws-instance-scheduler tutorial

### ISSUE THREAD

**Issue by andresbernasconi** [awslabs/aws-instance-scheduler#67]
When you follow the tutorial, it fails to say that there is a max amount of chars that a Rule may have (in this case the Cloudwatch Rule that triggers every 5 minutes). When the template creates a rule based on your Stack name, it adds more characters to it, cutting your name to fit the max char length requirement. When this happens, the Lambda python script fails to execute the cloudwatch rule, because it expects its full name to begin with the full name of your solution, and it doesn't. 

Possibe solutions are to match the incoming rule being fully contained in the other string or just match the first chars without the random part. [even though the documentation specifies the 36 chars limit, is not enforced anywhere. Mine had 37]

It would be nice to add extra logging to the solution in order to fully understand why there are / aren't instances being selected. In my case I had a misconfiguration on my side with the tag-names and no instance was being selected. After I added this log to ec2_services.py :115

logger.info("reservation_inst {} and tagname {}", reservation_inst, tagname)

and then I fixed it in 1'.

thanks for the solution.

**Comment by arieleeuw** [comment]
Hi,
We changed the logic in our next update that allows longer stacknames and checking of the rule name.
Regarding the logging, did you run the scheduler with CloudWatch Logging parameter enabled  in main template? This should give you mch more detailed information on selecting resources.

**Comment by shsenior** [comment]
Fixed in v1.2.0
