### ISSUE TITLE
Search lamba function in wrong region

### ISSUE THREAD

**Issue by prothorin** [awslabs/aws-instance-scheduler#7]
Search lamba function in wrong region (eu-central-1  instead ca-cental-1)

/usr/local/bin/scheduler-cli describe-schedules --region ca-central-1 --stack Scheduler

An error occurred (ResourceNotFoundException) when calling the Invoke operation: 
Function not found: arn:aws:lambda:eu-central-1:450193214715:function:Scheduler-InstanceSchedulerMain

Lambda functions: 
ca-canada-1 : 	Scheduler-InstanceSchedulerMain
ARN - 		arn:aws:lambda:ca-central-1:450193214715:function:Scheduler-InstanceSchedulerMain

CloudFormation:
Stack name: 	Scheduler
Stack ID:	arn:aws:cloudformation:ca-central-1:450193214715:stack/Scheduler/3f95eda0-1264-11e8-a312-504dce1555fe
Status: 	CREATE_COMPLETE
Parameters:
Regions		ca-central-1
DefaultTimezone	Canada/Central
TagName		Schedule

**Comment by arieleeuw** [comment]
We will fix this issue in a next maintenance release.

The line 113 in scheduler_cli.py
    lambda_client = boto3.client("lambda")

must be         
    lambda_client =_service_client("lambda", region=args.region)

**Comment by prothorin** [comment]
Thanks, working

**Comment by shsenior** [comment]
Fixed in v1.2.0
