### ISSUE TITLE
Can't find custom metrics

### ISSUE THREAD

**Issue by mrichman** [awslabs/aws-instance-scheduler#70]
I have `use_metrics: true` set, but I never see the custom metrics created.

I'm looking for this, per the [docs](https://docs.aws.amazon.com/solutions/latest/instance-scheduler/cloudwatch.html):
> In the Custom Namespaces drop-down field, choose InstanceScheduler:\<stackname\>.

but don't see it anywhere.

What am I doing wrong? The scheduler does indeed function, and has stopped my tagged instances per schedule.

**Comment by arieleeuw** [comment]
Hi,

In our first version there was an issue with the global metrics setting (which acts as the default), and metrics had to be enabled at schedule level. You can upgrade to the latest version from the AWS Answers page as we fixed this issue in version 1.1 or enable metrics per schedule. 

Hopes this help,
Arie

**Comment by mrichman** [comment]
@arieleeuw I just deployed whatever the latest CF stack is (2.2.2.0).

**Comment by arieleeuw** [comment]
For the custom resource the property is named "Metrics"
If you create the schedule using the CLI the option is  --use-metrics
The global parameter in the main stack is named "UseCloudWatchMetrics"

**Comment by shsenior** [comment]
Fixed in v1.2.0
