### ISSUE TITLE
How to enforce stop but not start the instances or enforcing the schedule ?

### ISSUE THREAD

**Issue by prateek121** [awslabs/aws-instance-scheduler#72]
I wanted to enable the enforcing of shutdown
 but should not be able to start the instances outside schedule hours

For ex: If schedule is "businessHours" -> 8AM  - 8PM 
If I try to start the instance at 7AM it should just shutdown and 
at the same time the scheduler shouldnt start the instance at 8am but just shutdown at 8pm.

**Comment by arieleeuw** [comment]
Hi,

We have the option to enforce a schedule using the enforced option for a schedule. This will make sure that:

If an instance is started outside of a running period in the schedule it will be stopped
If an instance is stopped inside a running period in the schedule it will be started

It is not possible to use this option with periods that just have a start or stop time

**Comment by vorkos** [comment]
Is there some option only stop instances on a schedule, but not to start it? (let the user decide when to start)

**Comment by arieleeuw** [comment]
Yes, this is possible by just setting the end time in a period.  Periods that just have a start or stop time cannot be combined with other periods in a schedule

**Comment by shsenior** [comment]
Resolving this issue. Please let us know if you have other questions.
