### ISSUE TITLE
Support for starting/stopping Elasticache clusters

### ISSUE THREAD

**Issue by electric** [awslabs/aws-instance-scheduler#78]
Hi,

I'd like to see support for starting and stopping nodes (some or all) in Elasticache clusters. Is this something that is likely to be supported any time soon?

Thanks

**Comment by electric** [comment]
Having just looked into this further, I realise that Elasticache itself doesn't support stopping clusters, so the likelihood of this feature being implemented is very, very low 😅

**Comment by shsenior** [comment]
Thank you for the suggestion. Yes you are correct that there are currently no plans to add Elasticache start/stop functionality at this time. Please re-open this issue or create another one in the future if the Elasticache behavior changes.
