### ISSUE TITLE
WaitStrategy class is not used

### ISSUE THREAD

**Issue by ilyash-b** [awslabs/aws-instance-scheduler#80]
`WaitStrategy` class is not used anywhere in the project, surprisingly enough not even as super class of `ConstantWaitStrategy`, `LinearWaitStrategy` and `MultiplyWaitStrategy`which are all defined in the same file as `WaitStrategy`.

**Comment by arieleeuw** [comment]
This is because it's part of a library we share between different solutions

**Comment by ilyash-b** [comment]
WAT? Are you sure? It's totally unintuitive and surprusing. Shared code should be refactored to some other `utils` project.

In addition why `...Strategy` classed don't inherit from `WaitStrategy` is still unclear.

**Comment by arieleeuw** [comment]
Thanks for your feedback, it's not copy and past but reuse of libraries between our solutions and we ship them as part of these solutions to avoid dependencies when deploying them. If another approach works better for your purpose you can fork the repository and change the code.

**Comment by ilyash-b** [comment]
> reuse of libraries between our solutions and we ship them as part of these solutions to avoid dependencies when deploying them

Can you elaborate on this please? Here are the options that I see:

1.  The file `aws-instance-scheduler/source/code/boto_retry/__init__.py` in the repository is output of a build. It doesn't have any comment in it about being generated. In this case it would be nice to add comments that say the file was generated.
1. The file `aws-instance-scheduler/source/code/boto_retry/__init__.py` has copy+pasted code. In this case it would be nice to add comments about the provenance of the `WaitStrategy` and related classes.
1. The file `aws-instance-scheduler/source/code/boto_retry/__init__.py` plainly has unused code without any good reason.

... and you keep forgetting to answer the inheritance question

**Comment by arieleeuw** [comment]
Thanks for for feedback, we’ll consider it for future development
