### ISSUE TITLE
Not working in eu-north-1

### ISSUE THREAD

**Issue by ianmorris8** [awslabs/aws-instance-scheduler#85]
I have the AWS instance scheduler installed and working but if I add eu-north-1 as a region I get the following in the logs

INFO : Handler SchedulerRequestHandler scheduling request for service(s) ec2, account(s) 
INFO : Running EC2 scheduler for account 1234567890 in region(s) eu-north-1
ERROR : eu-north-1 is not a valid region name

**Comment by arieleeuw** [comment]
Hi unfortunately this is an issue in the service API call that does not return this region. We will address this internally. For now you can make a small change to instance_scheduler.py (line append after line 90) to append the region.

```
89:        # valid regions for service
90:        self._valid_regions = boto3.Session().get_available_regions(service.service_name)
91:        self._valid_regions.append("eu-north-1")
```

We hope this resolves asap

**Comment by ianmorris8** [comment]
Thanks. That worked a treat.
