### ISSUE TITLE
How to modify code to support a new region (ap-east-1)?

### ISSUE THREAD

**Issue by philipho11** [awslabs/aws-instance-scheduler#90]
I got this error, seemingly due to unsupported for a new region ap-east-1

Error occurred while GetObject. S3 Error Code: IllegalLocationConstraintException. S3 Error Message: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: c87caec0-6a21-11e9-8eea-954572d77530)

**Comment by glenak1911** [comment]
I was able to get around this by specifying the `--region` flag and setting it to the region that the bucket was created in. 

For example, a bucket created in `us-east-1`:
`aws s3 cp s3://<bucket>/<prefix> ./<local_destination> --region us-east-1`

Hope this helps!

**Comment by shsenior** [comment]
Closing as @glenak1911 provided a solution to your question. Please re-open this issue if additional information is needed.
