### ISSUE TITLE
StartedTags StoppedTags timezone wrong

### ISSUE THREAD

**Issue by aparker-cityworks** [awslabs/aws-instance-scheduler#92]
I have a StartedTags and StoppedTags set using the {timezone} place holder.
I have DefaultTimezone set to UTC.
I have created a Schedule with a timezone setting of America/New_York.

When the instance was stopped using that schedule it was successfully tagged with:
`ScheduleMessage: Stopped on 2019/05/22 at 22:55 UTC`

You can see that the {timezone} placeholder inserted UTC for the timezone when I think it should have used 18:55 America/New_York.  It seems like the {timezone} placeholder and the time value is using the default timezone rather than the timezone from the Schedule.

Could this be modified to use the timezone setting from the Schedule if there is one?

**Comment by arieleeuw** [comment]
Bij design the date and time are always in UTC timezone.

**Comment by aparker-cityworks** [comment]
Ok, thanks for looking.
I just thought it made sense that if a Schedule had a timezone defined, and the instance was started or stopped based on that timezone then the time in the tags would reflect that timezone setting.
Not a big deal though, just a small, visual preference.

**Comment by shsenior** [comment]
Close as resolved.
