### ISSUE TITLE
Instance scheduler stack doesn't do anything

### ISSUE THREAD

**Issue by alanmcg** [awslabs/aws-instance-scheduler#94]
Been trying to get this working for a while now, followed the deployment guide:

https://docs.aws.amazon.com/solutions/latest/instance-scheduler/welcome.html

Everything gets created, everything is in the same region, I didn't modify the stack at all this time. Added tags to instances in the same account and region as per the default "Schedule =  office-hours" but the dynamodb state table never picks up the entries.

This is in eu-north-1, the instances are in a vpc which I have added in the lambda function under "network". I have added the policy "AWSLambdaVPCAccessExecutionRole" to the instance scheduler stack role. Still nothing, AWS support wont help as they say it's not "a supported solution". Even directly asked an AWS solutions architect im friends with but he didn't know much about it.

**Comment by arieleeuw** [comment]
https://github.com/awslabs/aws-instance-scheduler/issues/85 regarding eu-north issue.
Lamda does not need to be in VPC as it uses the public API to manage your instances.
Hope this helps

**Comment by alanmcg** [comment]
Thanks, however adding it to the vpc was a last resort, it didn't work before either. Not really sure how to proceed with troubleshooting this, are there any decent alternatives to this stack?

**Comment by arieleeuw** [comment]
Did you check issue #85 https://github.com/awslabs/aws-instance-scheduler/issues/85 ?
Any information in the logs?
