### ISSUE TITLE
Question into Custom::ServiceInstanceSchedule how can I put my own custom name?

### ISSUE THREAD

**Issue by ajobayer** [awslabs/aws-instance-scheduler#97]
SydneyOfficehoursPeriods:
Type: Custom::ServiceInstanceSchedule
Properties:
Description: Weekdays in Sydney
ServiceToken: arn:aws:lambda:ap-southeast-2::function:test-rds-scheduler-InstanceSchedulerMain
Enforced: 'True'
#Name: 'sydney-office-hours'
Timezone: Australia/Sydney
Periods:
- Description: Sydney Opening hours on weekdays
BeginTime: '07:00'
EndTime: '19:30'
#Name: 'sydney-office-hours'
WeekDays: Mon-Fri
-------------------
In the above cfn I would like to add the Scheduler tag name as Name: 'sydney-office-hours' 
so-that dont need to change the RDS tag name. How can I set my own custom name?

where in my RDS mentioned the tag as following:

Schedule: sydney-office-hours

**Comment by arieleeuw** [comment]
The v1.2 update that was released this week allows setting a schedule name

https://docs.aws.amazon.com/solutions/latest/instance-scheduler/appendix-d.html

On 13 Jun 2019, at 06:01, Abdullah Jobayer <notifications@github.com<mailto:notifications@github.com>> wrote:


SydneyOfficehoursPeriods:
Type: Custom::ServiceInstanceSchedule
Properties:
Description: Weekdays in Sydney
ServiceToken: arn:aws:lambda:ap-southeast-2::function:test-rds-scheduler-InstanceSchedulerMain
Enforced: 'True'
#Name: 'sydney-office-hours'
Timezone: Australia/Sydney
Periods:

  *   Description: Sydney Opening hours on weekdays
BeginTime: '07:00'
EndTime: '19:30'
#Name: 'sydney-office-hours'
WeekDays: Mon-Fri

________________________________

In the above cfn I would like to add the Scheduler tag name as Name: 'sydney-office-hours'
so-that dont need to change the RDS tag name. How can I set my own custom name?

where in my RDS mentioned the tag as following:

Schedule: sydney-office-hours

**Comment by ajobayer** [comment]
Thanks @arieleeuw for new release and share the information. I will test it asap.

Regards,
Abdullah Jobayer
