### ISSUE TITLE
SNS to notify when scheduler takes any action

### ISSUE THREAD

**Issue by jcwhisman** [awslabs/aws-instance-scheduler#98]
Hopefully I am not over stepping by using the issues section to make a suggestion.

The scheduler works great for us. However, there are many actions we have to take once the scheduler takes effect for our IaaS services.

Currently we are building outwatch rules, then within our lambdas, checking to see if the scheduler started/stopped the instance before taking action.

It would be awesome to be able to subscribe our lambdas to a topic to trigger these post-scheduled start/stop actions.

**Comment by jcwhisman** [comment]
Yes... Sorta.

For our use case, we are very IaaS driven. When the scheduler starts/stops we need to do things to notify other systems that stuff is happening to each EC2 Instance. Currently we are wrapping the AWS Scheduler with our own custom lambdas. We are triggering our own lambda on EC2 Start/Stop cloudtrail events that are coming from the Scheduler Role. I just thought it would be nice to us an SNS topic that our response lambdas can subscribe to instead of the hackey solution we have now.

Thanks for your response!

Hope that makes sense! Thanks for your response!

**Comment by Rayv1** [comment]
Hi guys.. any updates or  plans to implement this feature?

**Comment by maykays** [comment]
Hi @Rayv1 , our next release is focused on developing a CDK (eta Q3-20). This feature request is in our backlog.

**Comment by maykays** [comment]
Hi @Rayv1. We will not implement this feature after further review and discussion. The concern is this feature will generate too many emails/notifications, which makes for a bad customer experience. Instead, we recommend you write a filter for CloudWatch logs so you can select the notifications you want to receive.
