### ISSUE TITLE
Instance scheduler does not ignore disabled maintenance windows, fails to recognize active ones

### ISSUE THREAD

**Issue by georgematthew** [awslabs/aws-instance-scheduler#99]
The instance scheduler appears to get hung up on disabled maintenance windows, as they do not have a `NextExecutionTime`:
```
2019-06-19 - 13:45:12.901 - ERROR : Error loading ssm maintenace windows, ('NextExecutionTime')
2019-06-19 - 13:45:13.659 - ERROR : SSM maintenance window test-maintenance-window used in schedule AlwaysOff not found
```
This error was duplicated in a second AWS account by disabling an existing maintenance window and attempting to reference a second, active one in a schedule.

**Comment by georgebearden** [comment]
Thank you for opening this issue, George, and sorry for the delay. I've reproduced this issue. So one option would be to keep the value of the use_maintenance_window parameter in sync with state (enabled/disabled) of the maintenance window. This isn't ideal though... 

I think the better solution here would be to filter out disabled maintenance windows from the `describe_maintenance_windows` boto3 call as follows:

```
resp = ssm.describe_maintenance_windows(
        Filters=[
            {
                'Key': 'Enabled',
                'Values': [
                    'True'
                ]
            }
        ]
    )
```

Let me know your thoughts, and in the mean time I will be adding this bug fix to the Solutions backlog to be included in its next release.

**Comment by georgematthew** [comment]
Thank you, George. I've done some testing and this appears to work -  we will be updating our Lambda function code while waiting on the bugfix release.

**Comment by georgebearden** [comment]
This has been incorporated into the latest release.
